/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Late.Client;
using Late.Api;
// uncomment below to import models
//using Late.Model;

namespace Late.Test.Api
{
    /// <summary>
    ///  Class for testing LinkedInMentionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LinkedInMentionsApiTests : IDisposable
    {
        private LinkedInMentionsApi instance;

        public LinkedInMentionsApiTests()
        {
            instance = new LinkedInMentionsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinkedInMentionsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LinkedInMentionsApi
            //Assert.IsType<LinkedInMentionsApi>(instance);
        }

        /// <summary>
        /// Test GetLinkedInMentions
        /// </summary>
        [Fact]
        public void GetLinkedInMentionsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string url = null;
            //string? displayName = null;
            //var response = instance.GetLinkedInMentions(accountId, url, displayName);
            //Assert.IsType<GetLinkedInMentions200Response>(response);
        }
    }
}
