/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Late.Client;
using Late.Api;
// uncomment below to import models
//using Late.Model;

namespace Late.Test.Api
{
    /// <summary>
    ///  Class for testing LogsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LogsApiTests : IDisposable
    {
        private LogsApi instance;

        public LogsApiTests()
        {
            instance = new LogsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LogsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' LogsApi
            //Assert.IsType<LogsApi>(instance);
        }

        /// <summary>
        /// Test GetLog
        /// </summary>
        [Fact]
        public void GetLogTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string logId = null;
            //var response = instance.GetLog(logId);
            //Assert.IsType<GetLog200Response>(response);
        }

        /// <summary>
        /// Test GetPostLogs
        /// </summary>
        [Fact]
        public void GetPostLogsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string postId = null;
            //int? limit = null;
            //var response = instance.GetPostLogs(postId, limit);
            //Assert.IsType<GetPostLogs200Response>(response);
        }

        /// <summary>
        /// Test ListLogs
        /// </summary>
        [Fact]
        public void ListLogsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? status = null;
            //string? platform = null;
            //string? action = null;
            //int? days = null;
            //int? limit = null;
            //int? skip = null;
            //var response = instance.ListLogs(status, platform, action, days, limit, skip);
            //Assert.IsType<ListLogs200Response>(response);
        }
    }
}
