/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Late.Client;
using Late.Api;
// uncomment below to import models
//using Late.Model;

namespace Late.Test.Api
{
    /// <summary>
    ///  Class for testing WebhooksApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class WebhooksApiTests : IDisposable
    {
        private WebhooksApi instance;

        public WebhooksApiTests()
        {
            instance = new WebhooksApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhooksApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' WebhooksApi
            //Assert.IsType<WebhooksApi>(instance);
        }

        /// <summary>
        /// Test CreateWebhookSettings
        /// </summary>
        [Fact]
        public void CreateWebhookSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreateWebhookSettingsRequest createWebhookSettingsRequest = null;
            //var response = instance.CreateWebhookSettings(createWebhookSettingsRequest);
            //Assert.IsType<UpdateWebhookSettings200Response>(response);
        }

        /// <summary>
        /// Test DeleteWebhookSettings
        /// </summary>
        [Fact]
        public void DeleteWebhookSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.DeleteWebhookSettings(id);
            //Assert.IsType<UpdateRedditSubreddits200Response>(response);
        }

        /// <summary>
        /// Test GetWebhookLogs
        /// </summary>
        [Fact]
        public void GetWebhookLogsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string? status = null;
            //string? varEvent = null;
            //string? webhookId = null;
            //var response = instance.GetWebhookLogs(limit, status, varEvent, webhookId);
            //Assert.IsType<GetWebhookLogs200Response>(response);
        }

        /// <summary>
        /// Test GetWebhookSettings
        /// </summary>
        [Fact]
        public void GetWebhookSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetWebhookSettings();
            //Assert.IsType<GetWebhookSettings200Response>(response);
        }

        /// <summary>
        /// Test TestWebhook
        /// </summary>
        [Fact]
        public void TestWebhookTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TestWebhookRequest testWebhookRequest = null;
            //var response = instance.TestWebhook(testWebhookRequest);
            //Assert.IsType<TestWebhook200Response>(response);
        }

        /// <summary>
        /// Test UpdateWebhookSettings
        /// </summary>
        [Fact]
        public void UpdateWebhookSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //UpdateWebhookSettingsRequest updateWebhookSettingsRequest = null;
            //var response = instance.UpdateWebhookSettings(updateWebhookSettingsRequest);
            //Assert.IsType<UpdateWebhookSettings200Response>(response);
        }
    }
}
