/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Late.Client;
using Late.Model;

namespace Late.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountGroupsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a new account group
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountGroupRequest"></param>
        /// <returns>CreateAccountGroup201Response</returns>
        CreateAccountGroup201Response CreateAccountGroup(CreateAccountGroupRequest createAccountGroupRequest);

        /// <summary>
        /// Create a new account group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountGroupRequest"></param>
        /// <returns>ApiResponse of CreateAccountGroup201Response</returns>
        ApiResponse<CreateAccountGroup201Response> CreateAccountGroupWithHttpInfo(CreateAccountGroupRequest createAccountGroupRequest);
        /// <summary>
        /// Delete an account group
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <returns>DeleteAccountGroup200Response</returns>
        DeleteAccountGroup200Response DeleteAccountGroup(string groupId);

        /// <summary>
        /// Delete an account group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <returns>ApiResponse of DeleteAccountGroup200Response</returns>
        ApiResponse<DeleteAccountGroup200Response> DeleteAccountGroupWithHttpInfo(string groupId);
        /// <summary>
        /// List account groups for the authenticated user
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListAccountGroups200Response</returns>
        ListAccountGroups200Response ListAccountGroups();

        /// <summary>
        /// List account groups for the authenticated user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListAccountGroups200Response</returns>
        ApiResponse<ListAccountGroups200Response> ListAccountGroupsWithHttpInfo();
        /// <summary>
        /// Update an account group
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="updateAccountGroupRequest"></param>
        /// <returns>UpdateAccountGroup200Response</returns>
        UpdateAccountGroup200Response UpdateAccountGroup(string groupId, UpdateAccountGroupRequest updateAccountGroupRequest);

        /// <summary>
        /// Update an account group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="updateAccountGroupRequest"></param>
        /// <returns>ApiResponse of UpdateAccountGroup200Response</returns>
        ApiResponse<UpdateAccountGroup200Response> UpdateAccountGroupWithHttpInfo(string groupId, UpdateAccountGroupRequest updateAccountGroupRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountGroupsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create a new account group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountGroupRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateAccountGroup201Response</returns>
        System.Threading.Tasks.Task<CreateAccountGroup201Response> CreateAccountGroupAsync(CreateAccountGroupRequest createAccountGroupRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create a new account group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountGroupRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateAccountGroup201Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<CreateAccountGroup201Response>> CreateAccountGroupWithHttpInfoAsync(CreateAccountGroupRequest createAccountGroupRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Delete an account group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeleteAccountGroup200Response</returns>
        System.Threading.Tasks.Task<DeleteAccountGroup200Response> DeleteAccountGroupAsync(string groupId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete an account group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeleteAccountGroup200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeleteAccountGroup200Response>> DeleteAccountGroupWithHttpInfoAsync(string groupId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List account groups for the authenticated user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListAccountGroups200Response</returns>
        System.Threading.Tasks.Task<ListAccountGroups200Response> ListAccountGroupsAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List account groups for the authenticated user
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListAccountGroups200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<ListAccountGroups200Response>> ListAccountGroupsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Update an account group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="updateAccountGroupRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateAccountGroup200Response</returns>
        System.Threading.Tasks.Task<UpdateAccountGroup200Response> UpdateAccountGroupAsync(string groupId, UpdateAccountGroupRequest updateAccountGroupRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Update an account group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="updateAccountGroupRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateAccountGroup200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<UpdateAccountGroup200Response>> UpdateAccountGroupWithHttpInfoAsync(string groupId, UpdateAccountGroupRequest updateAccountGroupRequest, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountGroupsApi : IAccountGroupsApiSync, IAccountGroupsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AccountGroupsApi : IDisposable, IAccountGroupsApi
    {
        private Late.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountGroupsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public AccountGroupsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountGroupsApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public AccountGroupsApi(string basePath)
        {
            this.Configuration = Late.Client.Configuration.MergeConfigurations(
                Late.Client.GlobalConfiguration.Instance,
                new Late.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Late.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Late.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountGroupsApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public AccountGroupsApi(Late.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Late.Client.Configuration.MergeConfigurations(
                Late.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Late.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Late.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountGroupsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AccountGroupsApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountGroupsApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AccountGroupsApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Late.Client.Configuration.MergeConfigurations(
                Late.Client.GlobalConfiguration.Instance,
                new Late.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Late.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Late.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountGroupsApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public AccountGroupsApi(HttpClient client, Late.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Late.Client.Configuration.MergeConfigurations(
                Late.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Late.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Late.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountGroupsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public AccountGroupsApi(Late.Client.ISynchronousClient client, Late.Client.IAsynchronousClient asyncClient, Late.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Late.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Late.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Late.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Late.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Late.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Late.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create a new account group 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountGroupRequest"></param>
        /// <returns>CreateAccountGroup201Response</returns>
        public CreateAccountGroup201Response CreateAccountGroup(CreateAccountGroupRequest createAccountGroupRequest)
        {
            Late.Client.ApiResponse<CreateAccountGroup201Response> localVarResponse = CreateAccountGroupWithHttpInfo(createAccountGroupRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new account group 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountGroupRequest"></param>
        /// <returns>ApiResponse of CreateAccountGroup201Response</returns>
        public Late.Client.ApiResponse<CreateAccountGroup201Response> CreateAccountGroupWithHttpInfo(CreateAccountGroupRequest createAccountGroupRequest)
        {
            // verify the required parameter 'createAccountGroupRequest' is set
            if (createAccountGroupRequest == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'createAccountGroupRequest' when calling AccountGroupsApi->CreateAccountGroup");

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createAccountGroupRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CreateAccountGroup201Response>("/v1/account-groups", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateAccountGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new account group 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountGroupRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CreateAccountGroup201Response</returns>
        public async System.Threading.Tasks.Task<CreateAccountGroup201Response> CreateAccountGroupAsync(CreateAccountGroupRequest createAccountGroupRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Late.Client.ApiResponse<CreateAccountGroup201Response> localVarResponse = await CreateAccountGroupWithHttpInfoAsync(createAccountGroupRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new account group 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createAccountGroupRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CreateAccountGroup201Response)</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<CreateAccountGroup201Response>> CreateAccountGroupWithHttpInfoAsync(CreateAccountGroupRequest createAccountGroupRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createAccountGroupRequest' is set
            if (createAccountGroupRequest == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'createAccountGroupRequest' when calling AccountGroupsApi->CreateAccountGroup");


            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createAccountGroupRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<CreateAccountGroup201Response>("/v1/account-groups", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateAccountGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete an account group 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <returns>DeleteAccountGroup200Response</returns>
        public DeleteAccountGroup200Response DeleteAccountGroup(string groupId)
        {
            Late.Client.ApiResponse<DeleteAccountGroup200Response> localVarResponse = DeleteAccountGroupWithHttpInfo(groupId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete an account group 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <returns>ApiResponse of DeleteAccountGroup200Response</returns>
        public Late.Client.ApiResponse<DeleteAccountGroup200Response> DeleteAccountGroupWithHttpInfo(string groupId)
        {
            // verify the required parameter 'groupId' is set
            if (groupId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'groupId' when calling AccountGroupsApi->DeleteAccountGroup");

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("groupId", Late.Client.ClientUtils.ParameterToString(groupId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<DeleteAccountGroup200Response>("/v1/account-groups/{groupId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteAccountGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete an account group 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeleteAccountGroup200Response</returns>
        public async System.Threading.Tasks.Task<DeleteAccountGroup200Response> DeleteAccountGroupAsync(string groupId, System.Threading.CancellationToken cancellationToken = default)
        {
            Late.Client.ApiResponse<DeleteAccountGroup200Response> localVarResponse = await DeleteAccountGroupWithHttpInfoAsync(groupId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete an account group 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeleteAccountGroup200Response)</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<DeleteAccountGroup200Response>> DeleteAccountGroupWithHttpInfoAsync(string groupId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'groupId' is set
            if (groupId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'groupId' when calling AccountGroupsApi->DeleteAccountGroup");


            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("groupId", Late.Client.ClientUtils.ParameterToString(groupId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<DeleteAccountGroup200Response>("/v1/account-groups/{groupId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteAccountGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List account groups for the authenticated user 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ListAccountGroups200Response</returns>
        public ListAccountGroups200Response ListAccountGroups()
        {
            Late.Client.ApiResponse<ListAccountGroups200Response> localVarResponse = ListAccountGroupsWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List account groups for the authenticated user 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of ListAccountGroups200Response</returns>
        public Late.Client.ApiResponse<ListAccountGroups200Response> ListAccountGroupsWithHttpInfo()
        {
            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ListAccountGroups200Response>("/v1/account-groups", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListAccountGroups", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List account groups for the authenticated user 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ListAccountGroups200Response</returns>
        public async System.Threading.Tasks.Task<ListAccountGroups200Response> ListAccountGroupsAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            Late.Client.ApiResponse<ListAccountGroups200Response> localVarResponse = await ListAccountGroupsWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List account groups for the authenticated user 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ListAccountGroups200Response)</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<ListAccountGroups200Response>> ListAccountGroupsWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ListAccountGroups200Response>("/v1/account-groups", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListAccountGroups", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update an account group 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="updateAccountGroupRequest"></param>
        /// <returns>UpdateAccountGroup200Response</returns>
        public UpdateAccountGroup200Response UpdateAccountGroup(string groupId, UpdateAccountGroupRequest updateAccountGroupRequest)
        {
            Late.Client.ApiResponse<UpdateAccountGroup200Response> localVarResponse = UpdateAccountGroupWithHttpInfo(groupId, updateAccountGroupRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update an account group 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="updateAccountGroupRequest"></param>
        /// <returns>ApiResponse of UpdateAccountGroup200Response</returns>
        public Late.Client.ApiResponse<UpdateAccountGroup200Response> UpdateAccountGroupWithHttpInfo(string groupId, UpdateAccountGroupRequest updateAccountGroupRequest)
        {
            // verify the required parameter 'groupId' is set
            if (groupId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'groupId' when calling AccountGroupsApi->UpdateAccountGroup");

            // verify the required parameter 'updateAccountGroupRequest' is set
            if (updateAccountGroupRequest == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'updateAccountGroupRequest' when calling AccountGroupsApi->UpdateAccountGroup");

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("groupId", Late.Client.ClientUtils.ParameterToString(groupId)); // path parameter
            localVarRequestOptions.Data = updateAccountGroupRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<UpdateAccountGroup200Response>("/v1/account-groups/{groupId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateAccountGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update an account group 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="updateAccountGroupRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateAccountGroup200Response</returns>
        public async System.Threading.Tasks.Task<UpdateAccountGroup200Response> UpdateAccountGroupAsync(string groupId, UpdateAccountGroupRequest updateAccountGroupRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Late.Client.ApiResponse<UpdateAccountGroup200Response> localVarResponse = await UpdateAccountGroupWithHttpInfoAsync(groupId, updateAccountGroupRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update an account group 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="groupId"></param>
        /// <param name="updateAccountGroupRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateAccountGroup200Response)</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<UpdateAccountGroup200Response>> UpdateAccountGroupWithHttpInfoAsync(string groupId, UpdateAccountGroupRequest updateAccountGroupRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'groupId' is set
            if (groupId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'groupId' when calling AccountGroupsApi->UpdateAccountGroup");

            // verify the required parameter 'updateAccountGroupRequest' is set
            if (updateAccountGroupRequest == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'updateAccountGroupRequest' when calling AccountGroupsApi->UpdateAccountGroup");


            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("groupId", Late.Client.ClientUtils.ParameterToString(groupId)); // path parameter
            localVarRequestOptions.Data = updateAccountGroupRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<UpdateAccountGroup200Response>("/v1/account-groups/{groupId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateAccountGroup", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
