/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Late.Client;
using Late.Model;

namespace Late.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProfilesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create a new profile
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createProfileRequest"></param>
        /// <returns>ProfileCreateResponse</returns>
        ProfileCreateResponse CreateProfile(CreateProfileRequest createProfileRequest);

        /// <summary>
        /// Create a new profile
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createProfileRequest"></param>
        /// <returns>ApiResponse of ProfileCreateResponse</returns>
        ApiResponse<ProfileCreateResponse> CreateProfileWithHttpInfo(CreateProfileRequest createProfileRequest);
        /// <summary>
        /// Delete a profile (must have no connected accounts)
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <returns>DeleteAccountGroup200Response</returns>
        DeleteAccountGroup200Response DeleteProfile(string profileId);

        /// <summary>
        /// Delete a profile (must have no connected accounts)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <returns>ApiResponse of DeleteAccountGroup200Response</returns>
        ApiResponse<DeleteAccountGroup200Response> DeleteProfileWithHttpInfo(string profileId);
        /// <summary>
        /// Get a profile by id
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <returns>GetProfile200Response</returns>
        GetProfile200Response GetProfile(string profileId);

        /// <summary>
        /// Get a profile by id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <returns>ApiResponse of GetProfile200Response</returns>
        ApiResponse<GetProfile200Response> GetProfileWithHttpInfo(string profileId);
        /// <summary>
        /// List profiles visible to the authenticated user
        /// </summary>
        /// <remarks>
        /// Returns profiles within the user&#39;s plan limit. Profiles are sorted by creation date (oldest first). Use &#x60;includeOverLimit&#x3D;true&#x60; to include profiles that exceed the plan limit (for management/deletion purposes). 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="includeOverLimit">When true, includes profiles that exceed the user&#39;s plan limit. Over-limit profiles will have &#x60;isOverLimit: true&#x60; in the response. Useful for managing/deleting profiles after a plan downgrade.  (optional, default to false)</param>
        /// <returns>ProfilesListResponse</returns>
        ProfilesListResponse ListProfiles(bool? includeOverLimit = default);

        /// <summary>
        /// List profiles visible to the authenticated user
        /// </summary>
        /// <remarks>
        /// Returns profiles within the user&#39;s plan limit. Profiles are sorted by creation date (oldest first). Use &#x60;includeOverLimit&#x3D;true&#x60; to include profiles that exceed the plan limit (for management/deletion purposes). 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="includeOverLimit">When true, includes profiles that exceed the user&#39;s plan limit. Over-limit profiles will have &#x60;isOverLimit: true&#x60; in the response. Useful for managing/deleting profiles after a plan downgrade.  (optional, default to false)</param>
        /// <returns>ApiResponse of ProfilesListResponse</returns>
        ApiResponse<ProfilesListResponse> ListProfilesWithHttpInfo(bool? includeOverLimit = default);
        /// <summary>
        /// Update a profile
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="updateProfileRequest"></param>
        /// <returns>UpdateProfile200Response</returns>
        UpdateProfile200Response UpdateProfile(string profileId, UpdateProfileRequest updateProfileRequest);

        /// <summary>
        /// Update a profile
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="updateProfileRequest"></param>
        /// <returns>ApiResponse of UpdateProfile200Response</returns>
        ApiResponse<UpdateProfile200Response> UpdateProfileWithHttpInfo(string profileId, UpdateProfileRequest updateProfileRequest);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProfilesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create a new profile
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createProfileRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProfileCreateResponse</returns>
        System.Threading.Tasks.Task<ProfileCreateResponse> CreateProfileAsync(CreateProfileRequest createProfileRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Create a new profile
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createProfileRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProfileCreateResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ProfileCreateResponse>> CreateProfileWithHttpInfoAsync(CreateProfileRequest createProfileRequest, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Delete a profile (must have no connected accounts)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeleteAccountGroup200Response</returns>
        System.Threading.Tasks.Task<DeleteAccountGroup200Response> DeleteProfileAsync(string profileId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Delete a profile (must have no connected accounts)
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeleteAccountGroup200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<DeleteAccountGroup200Response>> DeleteProfileWithHttpInfoAsync(string profileId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Get a profile by id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetProfile200Response</returns>
        System.Threading.Tasks.Task<GetProfile200Response> GetProfileAsync(string profileId, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Get a profile by id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetProfile200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetProfile200Response>> GetProfileWithHttpInfoAsync(string profileId, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// List profiles visible to the authenticated user
        /// </summary>
        /// <remarks>
        /// Returns profiles within the user&#39;s plan limit. Profiles are sorted by creation date (oldest first). Use &#x60;includeOverLimit&#x3D;true&#x60; to include profiles that exceed the plan limit (for management/deletion purposes). 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="includeOverLimit">When true, includes profiles that exceed the user&#39;s plan limit. Over-limit profiles will have &#x60;isOverLimit: true&#x60; in the response. Useful for managing/deleting profiles after a plan downgrade.  (optional, default to false)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProfilesListResponse</returns>
        System.Threading.Tasks.Task<ProfilesListResponse> ListProfilesAsync(bool? includeOverLimit = default, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// List profiles visible to the authenticated user
        /// </summary>
        /// <remarks>
        /// Returns profiles within the user&#39;s plan limit. Profiles are sorted by creation date (oldest first). Use &#x60;includeOverLimit&#x3D;true&#x60; to include profiles that exceed the plan limit (for management/deletion purposes). 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="includeOverLimit">When true, includes profiles that exceed the user&#39;s plan limit. Over-limit profiles will have &#x60;isOverLimit: true&#x60; in the response. Useful for managing/deleting profiles after a plan downgrade.  (optional, default to false)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProfilesListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<ProfilesListResponse>> ListProfilesWithHttpInfoAsync(bool? includeOverLimit = default, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Update a profile
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="updateProfileRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateProfile200Response</returns>
        System.Threading.Tasks.Task<UpdateProfile200Response> UpdateProfileAsync(string profileId, UpdateProfileRequest updateProfileRequest, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Update a profile
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="updateProfileRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateProfile200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<UpdateProfile200Response>> UpdateProfileWithHttpInfoAsync(string profileId, UpdateProfileRequest updateProfileRequest, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IProfilesApi : IProfilesApiSync, IProfilesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ProfilesApi : IDisposable, IProfilesApi
    {
        private Late.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ProfilesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ProfilesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProfilesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ProfilesApi(string basePath)
        {
            this.Configuration = Late.Client.Configuration.MergeConfigurations(
                Late.Client.GlobalConfiguration.Instance,
                new Late.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Late.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Late.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProfilesApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ProfilesApi(Late.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Late.Client.Configuration.MergeConfigurations(
                Late.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Late.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Late.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProfilesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ProfilesApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProfilesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ProfilesApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Late.Client.Configuration.MergeConfigurations(
                Late.Client.GlobalConfiguration.Instance,
                new Late.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Late.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Late.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProfilesApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ProfilesApi(HttpClient client, Late.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Late.Client.Configuration.MergeConfigurations(
                Late.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Late.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Late.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ProfilesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ProfilesApi(Late.Client.ISynchronousClient client, Late.Client.IAsynchronousClient asyncClient, Late.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Late.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Late.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Late.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Late.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Late.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Late.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create a new profile 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createProfileRequest"></param>
        /// <returns>ProfileCreateResponse</returns>
        public ProfileCreateResponse CreateProfile(CreateProfileRequest createProfileRequest)
        {
            Late.Client.ApiResponse<ProfileCreateResponse> localVarResponse = CreateProfileWithHttpInfo(createProfileRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new profile 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createProfileRequest"></param>
        /// <returns>ApiResponse of ProfileCreateResponse</returns>
        public Late.Client.ApiResponse<ProfileCreateResponse> CreateProfileWithHttpInfo(CreateProfileRequest createProfileRequest)
        {
            // verify the required parameter 'createProfileRequest' is set
            if (createProfileRequest == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'createProfileRequest' when calling ProfilesApi->CreateProfile");

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createProfileRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<ProfileCreateResponse>("/v1/profiles", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateProfile", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create a new profile 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createProfileRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProfileCreateResponse</returns>
        public async System.Threading.Tasks.Task<ProfileCreateResponse> CreateProfileAsync(CreateProfileRequest createProfileRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Late.Client.ApiResponse<ProfileCreateResponse> localVarResponse = await CreateProfileWithHttpInfoAsync(createProfileRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new profile 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createProfileRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProfileCreateResponse)</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<ProfileCreateResponse>> CreateProfileWithHttpInfoAsync(CreateProfileRequest createProfileRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'createProfileRequest' is set
            if (createProfileRequest == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'createProfileRequest' when calling ProfilesApi->CreateProfile");


            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = createProfileRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<ProfileCreateResponse>("/v1/profiles", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateProfile", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a profile (must have no connected accounts) 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <returns>DeleteAccountGroup200Response</returns>
        public DeleteAccountGroup200Response DeleteProfile(string profileId)
        {
            Late.Client.ApiResponse<DeleteAccountGroup200Response> localVarResponse = DeleteProfileWithHttpInfo(profileId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a profile (must have no connected accounts) 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <returns>ApiResponse of DeleteAccountGroup200Response</returns>
        public Late.Client.ApiResponse<DeleteAccountGroup200Response> DeleteProfileWithHttpInfo(string profileId)
        {
            // verify the required parameter 'profileId' is set
            if (profileId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'profileId' when calling ProfilesApi->DeleteProfile");

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("profileId", Late.Client.ClientUtils.ParameterToString(profileId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<DeleteAccountGroup200Response>("/v1/profiles/{profileId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteProfile", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete a profile (must have no connected accounts) 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DeleteAccountGroup200Response</returns>
        public async System.Threading.Tasks.Task<DeleteAccountGroup200Response> DeleteProfileAsync(string profileId, System.Threading.CancellationToken cancellationToken = default)
        {
            Late.Client.ApiResponse<DeleteAccountGroup200Response> localVarResponse = await DeleteProfileWithHttpInfoAsync(profileId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete a profile (must have no connected accounts) 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DeleteAccountGroup200Response)</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<DeleteAccountGroup200Response>> DeleteProfileWithHttpInfoAsync(string profileId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'profileId' is set
            if (profileId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'profileId' when calling ProfilesApi->DeleteProfile");


            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("profileId", Late.Client.ClientUtils.ParameterToString(profileId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.DeleteAsync<DeleteAccountGroup200Response>("/v1/profiles/{profileId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteProfile", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a profile by id 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <returns>GetProfile200Response</returns>
        public GetProfile200Response GetProfile(string profileId)
        {
            Late.Client.ApiResponse<GetProfile200Response> localVarResponse = GetProfileWithHttpInfo(profileId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a profile by id 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <returns>ApiResponse of GetProfile200Response</returns>
        public Late.Client.ApiResponse<GetProfile200Response> GetProfileWithHttpInfo(string profileId)
        {
            // verify the required parameter 'profileId' is set
            if (profileId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'profileId' when calling ProfilesApi->GetProfile");

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("profileId", Late.Client.ClientUtils.ParameterToString(profileId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetProfile200Response>("/v1/profiles/{profileId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetProfile", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get a profile by id 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetProfile200Response</returns>
        public async System.Threading.Tasks.Task<GetProfile200Response> GetProfileAsync(string profileId, System.Threading.CancellationToken cancellationToken = default)
        {
            Late.Client.ApiResponse<GetProfile200Response> localVarResponse = await GetProfileWithHttpInfoAsync(profileId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get a profile by id 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetProfile200Response)</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<GetProfile200Response>> GetProfileWithHttpInfoAsync(string profileId, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'profileId' is set
            if (profileId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'profileId' when calling ProfilesApi->GetProfile");


            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("profileId", Late.Client.ClientUtils.ParameterToString(profileId)); // path parameter

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<GetProfile200Response>("/v1/profiles/{profileId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetProfile", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List profiles visible to the authenticated user Returns profiles within the user&#39;s plan limit. Profiles are sorted by creation date (oldest first). Use &#x60;includeOverLimit&#x3D;true&#x60; to include profiles that exceed the plan limit (for management/deletion purposes). 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="includeOverLimit">When true, includes profiles that exceed the user&#39;s plan limit. Over-limit profiles will have &#x60;isOverLimit: true&#x60; in the response. Useful for managing/deleting profiles after a plan downgrade.  (optional, default to false)</param>
        /// <returns>ProfilesListResponse</returns>
        public ProfilesListResponse ListProfiles(bool? includeOverLimit = default)
        {
            Late.Client.ApiResponse<ProfilesListResponse> localVarResponse = ListProfilesWithHttpInfo(includeOverLimit);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List profiles visible to the authenticated user Returns profiles within the user&#39;s plan limit. Profiles are sorted by creation date (oldest first). Use &#x60;includeOverLimit&#x3D;true&#x60; to include profiles that exceed the plan limit (for management/deletion purposes). 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="includeOverLimit">When true, includes profiles that exceed the user&#39;s plan limit. Over-limit profiles will have &#x60;isOverLimit: true&#x60; in the response. Useful for managing/deleting profiles after a plan downgrade.  (optional, default to false)</param>
        /// <returns>ApiResponse of ProfilesListResponse</returns>
        public Late.Client.ApiResponse<ProfilesListResponse> ListProfilesWithHttpInfo(bool? includeOverLimit = default)
        {
            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (includeOverLimit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "includeOverLimit", includeOverLimit));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<ProfilesListResponse>("/v1/profiles", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListProfiles", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// List profiles visible to the authenticated user Returns profiles within the user&#39;s plan limit. Profiles are sorted by creation date (oldest first). Use &#x60;includeOverLimit&#x3D;true&#x60; to include profiles that exceed the plan limit (for management/deletion purposes). 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="includeOverLimit">When true, includes profiles that exceed the user&#39;s plan limit. Over-limit profiles will have &#x60;isOverLimit: true&#x60; in the response. Useful for managing/deleting profiles after a plan downgrade.  (optional, default to false)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ProfilesListResponse</returns>
        public async System.Threading.Tasks.Task<ProfilesListResponse> ListProfilesAsync(bool? includeOverLimit = default, System.Threading.CancellationToken cancellationToken = default)
        {
            Late.Client.ApiResponse<ProfilesListResponse> localVarResponse = await ListProfilesWithHttpInfoAsync(includeOverLimit, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List profiles visible to the authenticated user Returns profiles within the user&#39;s plan limit. Profiles are sorted by creation date (oldest first). Use &#x60;includeOverLimit&#x3D;true&#x60; to include profiles that exceed the plan limit (for management/deletion purposes). 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="includeOverLimit">When true, includes profiles that exceed the user&#39;s plan limit. Over-limit profiles will have &#x60;isOverLimit: true&#x60; in the response. Useful for managing/deleting profiles after a plan downgrade.  (optional, default to false)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ProfilesListResponse)</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<ProfilesListResponse>> ListProfilesWithHttpInfoAsync(bool? includeOverLimit = default, System.Threading.CancellationToken cancellationToken = default)
        {

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (includeOverLimit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Late.Client.ClientUtils.ParameterToMultiMap("", "includeOverLimit", includeOverLimit));
            }

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<ProfilesListResponse>("/v1/profiles", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListProfiles", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update a profile 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="updateProfileRequest"></param>
        /// <returns>UpdateProfile200Response</returns>
        public UpdateProfile200Response UpdateProfile(string profileId, UpdateProfileRequest updateProfileRequest)
        {
            Late.Client.ApiResponse<UpdateProfile200Response> localVarResponse = UpdateProfileWithHttpInfo(profileId, updateProfileRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update a profile 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="updateProfileRequest"></param>
        /// <returns>ApiResponse of UpdateProfile200Response</returns>
        public Late.Client.ApiResponse<UpdateProfile200Response> UpdateProfileWithHttpInfo(string profileId, UpdateProfileRequest updateProfileRequest)
        {
            // verify the required parameter 'profileId' is set
            if (profileId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'profileId' when calling ProfilesApi->UpdateProfile");

            // verify the required parameter 'updateProfileRequest' is set
            if (updateProfileRequest == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'updateProfileRequest' when calling ProfilesApi->UpdateProfile");

            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("profileId", Late.Client.ClientUtils.ParameterToString(profileId)); // path parameter
            localVarRequestOptions.Data = updateProfileRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<UpdateProfile200Response>("/v1/profiles/{profileId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateProfile", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update a profile 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="updateProfileRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateProfile200Response</returns>
        public async System.Threading.Tasks.Task<UpdateProfile200Response> UpdateProfileAsync(string profileId, UpdateProfileRequest updateProfileRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            Late.Client.ApiResponse<UpdateProfile200Response> localVarResponse = await UpdateProfileWithHttpInfoAsync(profileId, updateProfileRequest, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update a profile 
        /// </summary>
        /// <exception cref="Late.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="profileId"></param>
        /// <param name="updateProfileRequest"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateProfile200Response)</returns>
        public async System.Threading.Tasks.Task<Late.Client.ApiResponse<UpdateProfile200Response>> UpdateProfileWithHttpInfoAsync(string profileId, UpdateProfileRequest updateProfileRequest, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'profileId' is set
            if (profileId == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'profileId' when calling ProfilesApi->UpdateProfile");

            // verify the required parameter 'updateProfileRequest' is set
            if (updateProfileRequest == null)
                throw new Late.Client.ApiException(400, "Missing required parameter 'updateProfileRequest' when calling ProfilesApi->UpdateProfile");


            Late.Client.RequestOptions localVarRequestOptions = new Late.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Late.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Late.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("profileId", Late.Client.ClientUtils.ParameterToString(profileId)); // path parameter
            localVarRequestOptions.Data = updateProfileRequest;

            // authentication (bearerAuth) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PutAsync<UpdateProfile200Response>("/v1/profiles/{profileId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateProfile", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
