/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// BoostPostRequest
    /// </summary>
    [DataContract(Name = "boostPost_request")]
    public partial class BoostPostRequest : IValidatableObject
    {
        /// <summary>
        /// Available goals vary by platform. Meta (Facebook/Instagram) and TikTok support all 7. LinkedIn supports all except app_promotion. Twitter/X supports engagement, traffic, awareness, video_views, app_promotion. Pinterest and Google Ads support only engagement, traffic, awareness, video_views.
        /// </summary>
        /// <value>Available goals vary by platform. Meta (Facebook/Instagram) and TikTok support all 7. LinkedIn supports all except app_promotion. Twitter/X supports engagement, traffic, awareness, video_views, app_promotion. Pinterest and Google Ads support only engagement, traffic, awareness, video_views.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum GoalEnum
        {
            /// <summary>
            /// Enum Engagement for value: engagement
            /// </summary>
            [EnumMember(Value = "engagement")]
            Engagement = 1,

            /// <summary>
            /// Enum Traffic for value: traffic
            /// </summary>
            [EnumMember(Value = "traffic")]
            Traffic = 2,

            /// <summary>
            /// Enum Awareness for value: awareness
            /// </summary>
            [EnumMember(Value = "awareness")]
            Awareness = 3,

            /// <summary>
            /// Enum VideoViews for value: video_views
            /// </summary>
            [EnumMember(Value = "video_views")]
            VideoViews = 4,

            /// <summary>
            /// Enum LeadGeneration for value: lead_generation
            /// </summary>
            [EnumMember(Value = "lead_generation")]
            LeadGeneration = 5,

            /// <summary>
            /// Enum Conversions for value: conversions
            /// </summary>
            [EnumMember(Value = "conversions")]
            Conversions = 6,

            /// <summary>
            /// Enum AppPromotion for value: app_promotion
            /// </summary>
            [EnumMember(Value = "app_promotion")]
            AppPromotion = 7
        }


        /// <summary>
        /// Available goals vary by platform. Meta (Facebook/Instagram) and TikTok support all 7. LinkedIn supports all except app_promotion. Twitter/X supports engagement, traffic, awareness, video_views, app_promotion. Pinterest and Google Ads support only engagement, traffic, awareness, video_views.
        /// </summary>
        /// <value>Available goals vary by platform. Meta (Facebook/Instagram) and TikTok support all 7. LinkedIn supports all except app_promotion. Twitter/X supports engagement, traffic, awareness, video_views, app_promotion. Pinterest and Google Ads support only engagement, traffic, awareness, video_views.</value>
        [DataMember(Name = "goal", IsRequired = true, EmitDefaultValue = true)]
        public GoalEnum Goal { get; set; }
        /// <summary>
        /// Defines SpecialAdCategories
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SpecialAdCategoriesEnum
        {
            /// <summary>
            /// Enum HOUSING for value: HOUSING
            /// </summary>
            [EnumMember(Value = "HOUSING")]
            HOUSING = 1,

            /// <summary>
            /// Enum EMPLOYMENT for value: EMPLOYMENT
            /// </summary>
            [EnumMember(Value = "EMPLOYMENT")]
            EMPLOYMENT = 2,

            /// <summary>
            /// Enum CREDIT for value: CREDIT
            /// </summary>
            [EnumMember(Value = "CREDIT")]
            CREDIT = 3,

            /// <summary>
            /// Enum ISSUESELECTIONSPOLITICS for value: ISSUES_ELECTIONS_POLITICS
            /// </summary>
            [EnumMember(Value = "ISSUES_ELECTIONS_POLITICS")]
            ISSUESELECTIONSPOLITICS = 4
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BoostPostRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BoostPostRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BoostPostRequest" /> class.
        /// </summary>
        /// <param name="postId">Zernio post ID (provide this or platformPostId).</param>
        /// <param name="platformPostId">Platform post ID (alternative to postId).</param>
        /// <param name="accountId">Social account ID (required).</param>
        /// <param name="adAccountId">Platform ad account ID (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="goal">Available goals vary by platform. Meta (Facebook/Instagram) and TikTok support all 7. LinkedIn supports all except app_promotion. Twitter/X supports engagement, traffic, awareness, video_views, app_promotion. Pinterest and Google Ads support only engagement, traffic, awareness, video_views. (required).</param>
        /// <param name="budget">budget (required).</param>
        /// <param name="currency">currency.</param>
        /// <param name="schedule">schedule.</param>
        /// <param name="targeting">targeting.</param>
        /// <param name="bidAmount">Max bid cap (Meta only).</param>
        /// <param name="tracking">tracking.</param>
        /// <param name="specialAdCategories">Meta only. Required for housing, employment, credit, or political ads..</param>
        /// <param name="dsaBeneficiary">Name of the legal entity benefiting from the ad. Required by Meta when targeting EU users (DSA Article 26). Not enforced at schema level; enforced server-side when targeting intersects EU member states. .</param>
        /// <param name="dsaPayor">Name of the legal entity paying for the ad. Required by Meta when targeting EU users (DSA Article 26). Note Meta API spelling: dsa_payor (not dsa_payer). .</param>
        public BoostPostRequest(string postId = default, string platformPostId = default, string accountId = default, string adAccountId = default, string name = default, GoalEnum goal = default, BoostPostRequestBudget budget = default, string currency = default, BoostPostRequestSchedule schedule = default, BoostPostRequestTargeting targeting = default, decimal bidAmount = default, BoostPostRequestTracking tracking = default, List<SpecialAdCategoriesEnum> specialAdCategories = default, string dsaBeneficiary = default, string dsaPayor = default)
        {
            // to ensure "accountId" is required (not null)
            if (accountId == null)
            {
                throw new ArgumentNullException("accountId is a required property for BoostPostRequest and cannot be null");
            }
            this.AccountId = accountId;
            // to ensure "adAccountId" is required (not null)
            if (adAccountId == null)
            {
                throw new ArgumentNullException("adAccountId is a required property for BoostPostRequest and cannot be null");
            }
            this.AdAccountId = adAccountId;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for BoostPostRequest and cannot be null");
            }
            this.Name = name;
            this.Goal = goal;
            // to ensure "budget" is required (not null)
            if (budget == null)
            {
                throw new ArgumentNullException("budget is a required property for BoostPostRequest and cannot be null");
            }
            this.Budget = budget;
            this.PostId = postId;
            this.PlatformPostId = platformPostId;
            this.Currency = currency;
            this.Schedule = schedule;
            this.Targeting = targeting;
            this.BidAmount = bidAmount;
            this.Tracking = tracking;
            this.SpecialAdCategories = specialAdCategories;
            this.DsaBeneficiary = dsaBeneficiary;
            this.DsaPayor = dsaPayor;
        }

        /// <summary>
        /// Zernio post ID (provide this or platformPostId)
        /// </summary>
        /// <value>Zernio post ID (provide this or platformPostId)</value>
        [DataMember(Name = "postId", EmitDefaultValue = false)]
        public string PostId { get; set; }

        /// <summary>
        /// Platform post ID (alternative to postId)
        /// </summary>
        /// <value>Platform post ID (alternative to postId)</value>
        [DataMember(Name = "platformPostId", EmitDefaultValue = false)]
        public string PlatformPostId { get; set; }

        /// <summary>
        /// Social account ID
        /// </summary>
        /// <value>Social account ID</value>
        [DataMember(Name = "accountId", IsRequired = true, EmitDefaultValue = true)]
        public string AccountId { get; set; }

        /// <summary>
        /// Platform ad account ID
        /// </summary>
        /// <value>Platform ad account ID</value>
        [DataMember(Name = "adAccountId", IsRequired = true, EmitDefaultValue = true)]
        public string AdAccountId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Budget
        /// </summary>
        [DataMember(Name = "budget", IsRequired = true, EmitDefaultValue = true)]
        public BoostPostRequestBudget Budget { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        /*
        <example>USD</example>
        */
        [DataMember(Name = "currency", EmitDefaultValue = false)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets Schedule
        /// </summary>
        [DataMember(Name = "schedule", EmitDefaultValue = false)]
        public BoostPostRequestSchedule Schedule { get; set; }

        /// <summary>
        /// Gets or Sets Targeting
        /// </summary>
        [DataMember(Name = "targeting", EmitDefaultValue = false)]
        public BoostPostRequestTargeting Targeting { get; set; }

        /// <summary>
        /// Max bid cap (Meta only)
        /// </summary>
        /// <value>Max bid cap (Meta only)</value>
        [DataMember(Name = "bidAmount", EmitDefaultValue = false)]
        public decimal BidAmount { get; set; }

        /// <summary>
        /// Gets or Sets Tracking
        /// </summary>
        [DataMember(Name = "tracking", EmitDefaultValue = false)]
        public BoostPostRequestTracking Tracking { get; set; }

        /// <summary>
        /// Meta only. Required for housing, employment, credit, or political ads.
        /// </summary>
        /// <value>Meta only. Required for housing, employment, credit, or political ads.</value>
        [DataMember(Name = "specialAdCategories", EmitDefaultValue = false)]
        public List<BoostPostRequest.SpecialAdCategoriesEnum> SpecialAdCategories { get; set; }

        /// <summary>
        /// Name of the legal entity benefiting from the ad. Required by Meta when targeting EU users (DSA Article 26). Not enforced at schema level; enforced server-side when targeting intersects EU member states. 
        /// </summary>
        /// <value>Name of the legal entity benefiting from the ad. Required by Meta when targeting EU users (DSA Article 26). Not enforced at schema level; enforced server-side when targeting intersects EU member states. </value>
        [DataMember(Name = "dsaBeneficiary", EmitDefaultValue = false)]
        public string DsaBeneficiary { get; set; }

        /// <summary>
        /// Name of the legal entity paying for the ad. Required by Meta when targeting EU users (DSA Article 26). Note Meta API spelling: dsa_payor (not dsa_payer). 
        /// </summary>
        /// <value>Name of the legal entity paying for the ad. Required by Meta when targeting EU users (DSA Article 26). Note Meta API spelling: dsa_payor (not dsa_payer). </value>
        [DataMember(Name = "dsaPayor", EmitDefaultValue = false)]
        public string DsaPayor { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BoostPostRequest {\n");
            sb.Append("  PostId: ").Append(PostId).Append("\n");
            sb.Append("  PlatformPostId: ").Append(PlatformPostId).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  AdAccountId: ").Append(AdAccountId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Goal: ").Append(Goal).Append("\n");
            sb.Append("  Budget: ").Append(Budget).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Schedule: ").Append(Schedule).Append("\n");
            sb.Append("  Targeting: ").Append(Targeting).Append("\n");
            sb.Append("  BidAmount: ").Append(BidAmount).Append("\n");
            sb.Append("  Tracking: ").Append(Tracking).Append("\n");
            sb.Append("  SpecialAdCategories: ").Append(SpecialAdCategories).Append("\n");
            sb.Append("  DsaBeneficiary: ").Append(DsaBeneficiary).Append("\n");
            sb.Append("  DsaPayor: ").Append(DsaPayor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 255.", new [] { "Name" });
            }

            // DsaBeneficiary (string) maxLength
            if (this.DsaBeneficiary != null && this.DsaBeneficiary.Length > 100)
            {
                yield return new ValidationResult("Invalid value for DsaBeneficiary, length must be less than 100.", new [] { "DsaBeneficiary" });
            }

            // DsaPayor (string) maxLength
            if (this.DsaPayor != null && this.DsaPayor.Length > 100)
            {
                yield return new ValidationResult("Invalid value for DsaPayor, length must be less than 100.", new [] { "DsaPayor" });
            }

            yield break;
        }
    }

}
