/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Zernio.Client.FileParameter;
using OpenAPIDateConverter = Zernio.Client.OpenAPIDateConverter;

namespace Zernio.Model
{
    /// <summary>
    /// Metronome users only. Aggregated X API call counts bucketed by price tier (backward-compat). For per-operation breakdown use &#x60;xApiCallsByOperation&#x60;. 
    /// </summary>
    [DataContract(Name = "UsageStats_usage_xApiCalls")]
    public partial class UsageStatsUsageXApiCalls : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UsageStatsUsageXApiCalls" /> class.
        /// </summary>
        /// <param name="xApi005">Calls at $0.005 per call (reads, list mgmt, bookmarks, etc.).</param>
        /// <param name="xApi010">Calls at $0.010 per call (publish/delete, DM reads, follows).</param>
        /// <param name="xApi015">Calls at $0.015 per call (sending DMs, follow actions).</param>
        public UsageStatsUsageXApiCalls(int xApi005 = default, int xApi010 = default, int xApi015 = default)
        {
            this.XApi005 = xApi005;
            this.XApi010 = xApi010;
            this.XApi015 = xApi015;
        }

        /// <summary>
        /// Calls at $0.005 per call (reads, list mgmt, bookmarks, etc.)
        /// </summary>
        /// <value>Calls at $0.005 per call (reads, list mgmt, bookmarks, etc.)</value>
        [DataMember(Name = "x_api_005", EmitDefaultValue = false)]
        public int XApi005 { get; set; }

        /// <summary>
        /// Calls at $0.010 per call (publish/delete, DM reads, follows)
        /// </summary>
        /// <value>Calls at $0.010 per call (publish/delete, DM reads, follows)</value>
        [DataMember(Name = "x_api_010", EmitDefaultValue = false)]
        public int XApi010 { get; set; }

        /// <summary>
        /// Calls at $0.015 per call (sending DMs, follow actions)
        /// </summary>
        /// <value>Calls at $0.015 per call (sending DMs, follow actions)</value>
        [DataMember(Name = "x_api_015", EmitDefaultValue = false)]
        public int XApi015 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UsageStatsUsageXApiCalls {\n");
            sb.Append("  XApi005: ").Append(XApi005).Append("\n");
            sb.Append("  XApi010: ").Append(XApi010).Append("\n");
            sb.Append("  XApi015: ").Append(XApi015).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
