/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing AnalyticsOverview
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AnalyticsOverviewTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AnalyticsOverview
        //private AnalyticsOverview instance;

        public AnalyticsOverviewTests()
        {
            // TODO uncomment below to create an instance of AnalyticsOverview
            //instance = new AnalyticsOverview();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalyticsOverview
        /// </summary>
        [Fact]
        public void AnalyticsOverviewInstanceTest()
        {
            // TODO uncomment below to test "IsType" AnalyticsOverview
            //Assert.IsType<AnalyticsOverview>(instance);
        }

        /// <summary>
        /// Test the property 'TotalPosts'
        /// </summary>
        [Fact]
        public void TotalPostsTest()
        {
            // TODO unit test for the property 'TotalPosts'
        }

        /// <summary>
        /// Test the property 'PublishedPosts'
        /// </summary>
        [Fact]
        public void PublishedPostsTest()
        {
            // TODO unit test for the property 'PublishedPosts'
        }

        /// <summary>
        /// Test the property 'ScheduledPosts'
        /// </summary>
        [Fact]
        public void ScheduledPostsTest()
        {
            // TODO unit test for the property 'ScheduledPosts'
        }

        /// <summary>
        /// Test the property 'LastSync'
        /// </summary>
        [Fact]
        public void LastSyncTest()
        {
            // TODO unit test for the property 'LastSync'
        }
    }
}
