/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing AnalyticsSinglePostResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AnalyticsSinglePostResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AnalyticsSinglePostResponse
        //private AnalyticsSinglePostResponse instance;

        public AnalyticsSinglePostResponseTests()
        {
            // TODO uncomment below to create an instance of AnalyticsSinglePostResponse
            //instance = new AnalyticsSinglePostResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AnalyticsSinglePostResponse
        /// </summary>
        [Fact]
        public void AnalyticsSinglePostResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AnalyticsSinglePostResponse
            //Assert.IsType<AnalyticsSinglePostResponse>(instance);
        }

        /// <summary>
        /// Test the property 'PostId'
        /// </summary>
        [Fact]
        public void PostIdTest()
        {
            // TODO unit test for the property 'PostId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'ScheduledFor'
        /// </summary>
        [Fact]
        public void ScheduledForTest()
        {
            // TODO unit test for the property 'ScheduledFor'
        }

        /// <summary>
        /// Test the property 'PublishedAt'
        /// </summary>
        [Fact]
        public void PublishedAtTest()
        {
            // TODO unit test for the property 'PublishedAt'
        }

        /// <summary>
        /// Test the property 'Analytics'
        /// </summary>
        [Fact]
        public void AnalyticsTest()
        {
            // TODO unit test for the property 'Analytics'
        }

        /// <summary>
        /// Test the property 'PlatformAnalytics'
        /// </summary>
        [Fact]
        public void PlatformAnalyticsTest()
        {
            // TODO unit test for the property 'PlatformAnalytics'
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'PlatformPostUrl'
        /// </summary>
        [Fact]
        public void PlatformPostUrlTest()
        {
            // TODO unit test for the property 'PlatformPostUrl'
        }

        /// <summary>
        /// Test the property 'IsExternal'
        /// </summary>
        [Fact]
        public void IsExternalTest()
        {
            // TODO unit test for the property 'IsExternal'
        }
    }
}
