/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing BulkUploadPosts200ResponseErrorsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BulkUploadPosts200ResponseErrorsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BulkUploadPosts200ResponseErrorsInner
        //private BulkUploadPosts200ResponseErrorsInner instance;

        public BulkUploadPosts200ResponseErrorsInnerTests()
        {
            // TODO uncomment below to create an instance of BulkUploadPosts200ResponseErrorsInner
            //instance = new BulkUploadPosts200ResponseErrorsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BulkUploadPosts200ResponseErrorsInner
        /// </summary>
        [Fact]
        public void BulkUploadPosts200ResponseErrorsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" BulkUploadPosts200ResponseErrorsInner
            //Assert.IsType<BulkUploadPosts200ResponseErrorsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Row'
        /// </summary>
        [Fact]
        public void RowTest()
        {
            // TODO unit test for the property 'Row'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
