/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing BulkUploadPosts200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BulkUploadPosts200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BulkUploadPosts200Response
        //private BulkUploadPosts200Response instance;

        public BulkUploadPosts200ResponseTests()
        {
            // TODO uncomment below to create an instance of BulkUploadPosts200Response
            //instance = new BulkUploadPosts200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BulkUploadPosts200Response
        /// </summary>
        [Fact]
        public void BulkUploadPosts200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BulkUploadPosts200Response
            //Assert.IsType<BulkUploadPosts200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'TotalRows'
        /// </summary>
        [Fact]
        public void TotalRowsTest()
        {
            // TODO unit test for the property 'TotalRows'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Failed'
        /// </summary>
        [Fact]
        public void FailedTest()
        {
            // TODO unit test for the property 'Failed'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }

        /// <summary>
        /// Test the property 'Posts'
        /// </summary>
        [Fact]
        public void PostsTest()
        {
            // TODO unit test for the property 'Posts'
        }
    }
}
