/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing CheckInstagramHashtags200ResponseResultsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CheckInstagramHashtags200ResponseResultsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CheckInstagramHashtags200ResponseResultsInner
        //private CheckInstagramHashtags200ResponseResultsInner instance;

        public CheckInstagramHashtags200ResponseResultsInnerTests()
        {
            // TODO uncomment below to create an instance of CheckInstagramHashtags200ResponseResultsInner
            //instance = new CheckInstagramHashtags200ResponseResultsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CheckInstagramHashtags200ResponseResultsInner
        /// </summary>
        [Fact]
        public void CheckInstagramHashtags200ResponseResultsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" CheckInstagramHashtags200ResponseResultsInner
            //Assert.IsType<CheckInstagramHashtags200ResponseResultsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Hashtag'
        /// </summary>
        [Fact]
        public void HashtagTest()
        {
            // TODO unit test for the property 'Hashtag'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

        /// <summary>
        /// Test the property 'Confidence'
        /// </summary>
        [Fact]
        public void ConfidenceTest()
        {
            // TODO unit test for the property 'Confidence'
        }
    }
}
