/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing ConnectionLogError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConnectionLogErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConnectionLogError
        //private ConnectionLogError instance;

        public ConnectionLogErrorTests()
        {
            // TODO uncomment below to create an instance of ConnectionLogError
            //instance = new ConnectionLogError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConnectionLogError
        /// </summary>
        [Fact]
        public void ConnectionLogErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConnectionLogError
            //Assert.IsType<ConnectionLogError>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'RawResponse'
        /// </summary>
        [Fact]
        public void RawResponseTest()
        {
            // TODO unit test for the property 'RawResponse'
        }
    }
}
