/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing CreateWhatsAppContactRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateWhatsAppContactRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateWhatsAppContactRequest
        //private CreateWhatsAppContactRequest instance;

        public CreateWhatsAppContactRequestTests()
        {
            // TODO uncomment below to create an instance of CreateWhatsAppContactRequest
            //instance = new CreateWhatsAppContactRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateWhatsAppContactRequest
        /// </summary>
        [Fact]
        public void CreateWhatsAppContactRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateWhatsAppContactRequest
            //Assert.IsType<CreateWhatsAppContactRequest>(instance);
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Fact]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Fact]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }

        /// <summary>
        /// Test the property 'IsOptedIn'
        /// </summary>
        [Fact]
        public void IsOptedInTest()
        {
            // TODO unit test for the property 'IsOptedIn'
        }

        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Fact]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }

        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Fact]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
    }
}
