/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing CreateAccountGroupRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateAccountGroupRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateAccountGroupRequest
        //private CreateAccountGroupRequest instance;

        public CreateAccountGroupRequestTests()
        {
            // TODO uncomment below to create an instance of CreateAccountGroupRequest
            //instance = new CreateAccountGroupRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateAccountGroupRequest
        /// </summary>
        [Fact]
        public void CreateAccountGroupRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateAccountGroupRequest
            //Assert.IsType<CreateAccountGroupRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'AccountIds'
        /// </summary>
        [Fact]
        public void AccountIdsTest()
        {
            // TODO unit test for the property 'AccountIds'
        }
    }
}
