/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing DeleteWhatsAppGroupRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeleteWhatsAppGroupRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeleteWhatsAppGroupRequest
        //private DeleteWhatsAppGroupRequest instance;

        public DeleteWhatsAppGroupRequestTests()
        {
            // TODO uncomment below to create an instance of DeleteWhatsAppGroupRequest
            //instance = new DeleteWhatsAppGroupRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeleteWhatsAppGroupRequest
        /// </summary>
        [Fact]
        public void DeleteWhatsAppGroupRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeleteWhatsAppGroupRequest
            //Assert.IsType<DeleteWhatsAppGroupRequest>(instance);
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }

        /// <summary>
        /// Test the property 'GroupName'
        /// </summary>
        [Fact]
        public void GroupNameTest()
        {
            // TODO unit test for the property 'GroupName'
        }
    }
}
