/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing DeleteGoogleBusinessPlaceAction200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeleteGoogleBusinessPlaceAction200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeleteGoogleBusinessPlaceAction200Response
        //private DeleteGoogleBusinessPlaceAction200Response instance;

        public DeleteGoogleBusinessPlaceAction200ResponseTests()
        {
            // TODO uncomment below to create an instance of DeleteGoogleBusinessPlaceAction200Response
            //instance = new DeleteGoogleBusinessPlaceAction200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeleteGoogleBusinessPlaceAction200Response
        /// </summary>
        [Fact]
        public void DeleteGoogleBusinessPlaceAction200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeleteGoogleBusinessPlaceAction200Response
            //Assert.IsType<DeleteGoogleBusinessPlaceAction200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
