/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing DownloadTikTokVideo200ResponseFormatsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DownloadTikTokVideo200ResponseFormatsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DownloadTikTokVideo200ResponseFormatsInner
        //private DownloadTikTokVideo200ResponseFormatsInner instance;

        public DownloadTikTokVideo200ResponseFormatsInnerTests()
        {
            // TODO uncomment below to create an instance of DownloadTikTokVideo200ResponseFormatsInner
            //instance = new DownloadTikTokVideo200ResponseFormatsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DownloadTikTokVideo200ResponseFormatsInner
        /// </summary>
        [Fact]
        public void DownloadTikTokVideo200ResponseFormatsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" DownloadTikTokVideo200ResponseFormatsInner
            //Assert.IsType<DownloadTikTokVideo200ResponseFormatsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Ext'
        /// </summary>
        [Fact]
        public void ExtTest()
        {
            // TODO unit test for the property 'Ext'
        }
    }
}
