/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing DownloadFormat
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DownloadFormatTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DownloadFormat
        //private DownloadFormat instance;

        public DownloadFormatTests()
        {
            // TODO uncomment below to create an instance of DownloadFormat
            //instance = new DownloadFormat();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DownloadFormat
        /// </summary>
        [Fact]
        public void DownloadFormatInstanceTest()
        {
            // TODO uncomment below to test "IsType" DownloadFormat
            //Assert.IsType<DownloadFormat>(instance);
        }

        /// <summary>
        /// Test the property 'FormatId'
        /// </summary>
        [Fact]
        public void FormatIdTest()
        {
            // TODO unit test for the property 'FormatId'
        }

        /// <summary>
        /// Test the property 'Ext'
        /// </summary>
        [Fact]
        public void ExtTest()
        {
            // TODO unit test for the property 'Ext'
        }

        /// <summary>
        /// Test the property 'Resolution'
        /// </summary>
        [Fact]
        public void ResolutionTest()
        {
            // TODO unit test for the property 'Resolution'
        }

        /// <summary>
        /// Test the property 'Filesize'
        /// </summary>
        [Fact]
        public void FilesizeTest()
        {
            // TODO unit test for the property 'Filesize'
        }

        /// <summary>
        /// Test the property 'Quality'
        /// </summary>
        [Fact]
        public void QualityTest()
        {
            // TODO unit test for the property 'Quality'
        }
    }
}
