/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing DownloadFacebookVideo200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DownloadFacebookVideo200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DownloadFacebookVideo200Response
        //private DownloadFacebookVideo200Response instance;

        public DownloadFacebookVideo200ResponseTests()
        {
            // TODO uncomment below to create an instance of DownloadFacebookVideo200Response
            //instance = new DownloadFacebookVideo200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DownloadFacebookVideo200Response
        /// </summary>
        [Fact]
        public void DownloadFacebookVideo200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" DownloadFacebookVideo200Response
            //Assert.IsType<DownloadFacebookVideo200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'DownloadUrl'
        /// </summary>
        [Fact]
        public void DownloadUrlTest()
        {
            // TODO unit test for the property 'DownloadUrl'
        }

        /// <summary>
        /// Test the property 'Thumbnail'
        /// </summary>
        [Fact]
        public void ThumbnailTest()
        {
            // TODO unit test for the property 'Thumbnail'
        }
    }
}
