/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing FacebookPlatformData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FacebookPlatformDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FacebookPlatformData
        //private FacebookPlatformData instance;

        public FacebookPlatformDataTests()
        {
            // TODO uncomment below to create an instance of FacebookPlatformData
            //instance = new FacebookPlatformData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FacebookPlatformData
        /// </summary>
        [Fact]
        public void FacebookPlatformDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" FacebookPlatformData
            //Assert.IsType<FacebookPlatformData>(instance);
        }

        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Fact]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }

        /// <summary>
        /// Test the property 'FirstComment'
        /// </summary>
        [Fact]
        public void FirstCommentTest()
        {
            // TODO unit test for the property 'FirstComment'
        }

        /// <summary>
        /// Test the property 'PageId'
        /// </summary>
        [Fact]
        public void PageIdTest()
        {
            // TODO unit test for the property 'PageId'
        }
    }
}
