/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing GetGoogleBusinessLocationDetails200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetGoogleBusinessLocationDetails200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetGoogleBusinessLocationDetails200Response
        //private GetGoogleBusinessLocationDetails200Response instance;

        public GetGoogleBusinessLocationDetails200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetGoogleBusinessLocationDetails200Response
            //instance = new GetGoogleBusinessLocationDetails200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetGoogleBusinessLocationDetails200Response
        /// </summary>
        [Fact]
        public void GetGoogleBusinessLocationDetails200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetGoogleBusinessLocationDetails200Response
            //Assert.IsType<GetGoogleBusinessLocationDetails200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Fact]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }

        /// <summary>
        /// Test the property 'LocationId'
        /// </summary>
        [Fact]
        public void LocationIdTest()
        {
            // TODO unit test for the property 'LocationId'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'RegularHours'
        /// </summary>
        [Fact]
        public void RegularHoursTest()
        {
            // TODO unit test for the property 'RegularHours'
        }

        /// <summary>
        /// Test the property 'SpecialHours'
        /// </summary>
        [Fact]
        public void SpecialHoursTest()
        {
            // TODO unit test for the property 'SpecialHours'
        }

        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Fact]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }

        /// <summary>
        /// Test the property 'WebsiteUri'
        /// </summary>
        [Fact]
        public void WebsiteUriTest()
        {
            // TODO unit test for the property 'WebsiteUri'
        }

        /// <summary>
        /// Test the property 'PhoneNumbers'
        /// </summary>
        [Fact]
        public void PhoneNumbersTest()
        {
            // TODO unit test for the property 'PhoneNumbers'
        }
    }
}
