/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing GetInboxConversationMessages200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetInboxConversationMessages200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetInboxConversationMessages200Response
        //private GetInboxConversationMessages200Response instance;

        public GetInboxConversationMessages200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetInboxConversationMessages200Response
            //instance = new GetInboxConversationMessages200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetInboxConversationMessages200Response
        /// </summary>
        [Fact]
        public void GetInboxConversationMessages200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetInboxConversationMessages200Response
            //Assert.IsType<GetInboxConversationMessages200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Messages'
        /// </summary>
        [Fact]
        public void MessagesTest()
        {
            // TODO unit test for the property 'Messages'
        }

        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Fact]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }
    }
}
