/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing GetLog200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetLog200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetLog200Response
        //private GetLog200Response instance;

        public GetLog200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetLog200Response
            //instance = new GetLog200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetLog200Response
        /// </summary>
        [Fact]
        public void GetLog200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetLog200Response
            //Assert.IsType<GetLog200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Log'
        /// </summary>
        [Fact]
        public void LogTest()
        {
            // TODO unit test for the property 'Log'
        }
    }
}
