/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing GetPostLogs200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetPostLogs200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetPostLogs200Response
        //private GetPostLogs200Response instance;

        public GetPostLogs200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetPostLogs200Response
            //instance = new GetPostLogs200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetPostLogs200Response
        /// </summary>
        [Fact]
        public void GetPostLogs200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetPostLogs200Response
            //Assert.IsType<GetPostLogs200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Logs'
        /// </summary>
        [Fact]
        public void LogsTest()
        {
            // TODO unit test for the property 'Logs'
        }

        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Fact]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }

        /// <summary>
        /// Test the property 'PostId'
        /// </summary>
        [Fact]
        public void PostIdTest()
        {
            // TODO unit test for the property 'PostId'
        }
    }
}
