/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing GetWhatsAppBroadcastRecipients200ResponseSummary
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetWhatsAppBroadcastRecipients200ResponseSummaryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetWhatsAppBroadcastRecipients200ResponseSummary
        //private GetWhatsAppBroadcastRecipients200ResponseSummary instance;

        public GetWhatsAppBroadcastRecipients200ResponseSummaryTests()
        {
            // TODO uncomment below to create an instance of GetWhatsAppBroadcastRecipients200ResponseSummary
            //instance = new GetWhatsAppBroadcastRecipients200ResponseSummary();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetWhatsAppBroadcastRecipients200ResponseSummary
        /// </summary>
        [Fact]
        public void GetWhatsAppBroadcastRecipients200ResponseSummaryInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetWhatsAppBroadcastRecipients200ResponseSummary
            //Assert.IsType<GetWhatsAppBroadcastRecipients200ResponseSummary>(instance);
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'Pending'
        /// </summary>
        [Fact]
        public void PendingTest()
        {
            // TODO unit test for the property 'Pending'
        }

        /// <summary>
        /// Test the property 'Sent'
        /// </summary>
        [Fact]
        public void SentTest()
        {
            // TODO unit test for the property 'Sent'
        }

        /// <summary>
        /// Test the property 'Delivered'
        /// </summary>
        [Fact]
        public void DeliveredTest()
        {
            // TODO unit test for the property 'Delivered'
        }

        /// <summary>
        /// Test the property 'Read'
        /// </summary>
        [Fact]
        public void ReadTest()
        {
            // TODO unit test for the property 'Read'
        }

        /// <summary>
        /// Test the property 'Failed'
        /// </summary>
        [Fact]
        public void FailedTest()
        {
            // TODO unit test for the property 'Failed'
        }
    }
}
