/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing GetWhatsAppBroadcastRecipients200ResponseRecipientsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetWhatsAppBroadcastRecipients200ResponseRecipientsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetWhatsAppBroadcastRecipients200ResponseRecipientsInner
        //private GetWhatsAppBroadcastRecipients200ResponseRecipientsInner instance;

        public GetWhatsAppBroadcastRecipients200ResponseRecipientsInnerTests()
        {
            // TODO uncomment below to create an instance of GetWhatsAppBroadcastRecipients200ResponseRecipientsInner
            //instance = new GetWhatsAppBroadcastRecipients200ResponseRecipientsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetWhatsAppBroadcastRecipients200ResponseRecipientsInner
        /// </summary>
        [Fact]
        public void GetWhatsAppBroadcastRecipients200ResponseRecipientsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetWhatsAppBroadcastRecipients200ResponseRecipientsInner
            //Assert.IsType<GetWhatsAppBroadcastRecipients200ResponseRecipientsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Variables'
        /// </summary>
        [Fact]
        public void VariablesTest()
        {
            // TODO unit test for the property 'Variables'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Fact]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }

        /// <summary>
        /// Test the property 'SentAt'
        /// </summary>
        [Fact]
        public void SentAtTest()
        {
            // TODO unit test for the property 'SentAt'
        }

        /// <summary>
        /// Test the property 'DeliveredAt'
        /// </summary>
        [Fact]
        public void DeliveredAtTest()
        {
            // TODO unit test for the property 'DeliveredAt'
        }

        /// <summary>
        /// Test the property 'ReadAt'
        /// </summary>
        [Fact]
        public void ReadAtTest()
        {
            // TODO unit test for the property 'ReadAt'
        }
    }
}
