/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing GetWhatsAppContacts200ResponseFilters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetWhatsAppContacts200ResponseFiltersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetWhatsAppContacts200ResponseFilters
        //private GetWhatsAppContacts200ResponseFilters instance;

        public GetWhatsAppContacts200ResponseFiltersTests()
        {
            // TODO uncomment below to create an instance of GetWhatsAppContacts200ResponseFilters
            //instance = new GetWhatsAppContacts200ResponseFilters();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetWhatsAppContacts200ResponseFilters
        /// </summary>
        [Fact]
        public void GetWhatsAppContacts200ResponseFiltersInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetWhatsAppContacts200ResponseFilters
            //Assert.IsType<GetWhatsAppContacts200ResponseFilters>(instance);
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Fact]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }
    }
}
