/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing GoogleBusinessPlatformData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GoogleBusinessPlatformDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GoogleBusinessPlatformData
        //private GoogleBusinessPlatformData instance;

        public GoogleBusinessPlatformDataTests()
        {
            // TODO uncomment below to create an instance of GoogleBusinessPlatformData
            //instance = new GoogleBusinessPlatformData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GoogleBusinessPlatformData
        /// </summary>
        [Fact]
        public void GoogleBusinessPlatformDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" GoogleBusinessPlatformData
            //Assert.IsType<GoogleBusinessPlatformData>(instance);
        }

        /// <summary>
        /// Test the property 'LocationId'
        /// </summary>
        [Fact]
        public void LocationIdTest()
        {
            // TODO unit test for the property 'LocationId'
        }

        /// <summary>
        /// Test the property 'CallToAction'
        /// </summary>
        [Fact]
        public void CallToActionTest()
        {
            // TODO unit test for the property 'CallToAction'
        }
    }
}
