/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing ImportWhatsAppContacts200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImportWhatsAppContacts200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImportWhatsAppContacts200Response
        //private ImportWhatsAppContacts200Response instance;

        public ImportWhatsAppContacts200ResponseTests()
        {
            // TODO uncomment below to create an instance of ImportWhatsAppContacts200Response
            //instance = new ImportWhatsAppContacts200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImportWhatsAppContacts200Response
        /// </summary>
        [Fact]
        public void ImportWhatsAppContacts200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImportWhatsAppContacts200Response
            //Assert.IsType<ImportWhatsAppContacts200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }

        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }
    }
}
