/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing ImportWhatsAppContacts200ResponseResultsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ImportWhatsAppContacts200ResponseResultsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ImportWhatsAppContacts200ResponseResultsInner
        //private ImportWhatsAppContacts200ResponseResultsInner instance;

        public ImportWhatsAppContacts200ResponseResultsInnerTests()
        {
            // TODO uncomment below to create an instance of ImportWhatsAppContacts200ResponseResultsInner
            //instance = new ImportWhatsAppContacts200ResponseResultsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImportWhatsAppContacts200ResponseResultsInner
        /// </summary>
        [Fact]
        public void ImportWhatsAppContacts200ResponseResultsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ImportWhatsAppContacts200ResponseResultsInner
            //Assert.IsType<ImportWhatsAppContacts200ResponseResultsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'ContactId'
        /// </summary>
        [Fact]
        public void ContactIdTest()
        {
            // TODO unit test for the property 'ContactId'
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
