/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing ListPostsLogs200ResponsePagination
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListPostsLogs200ResponsePaginationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListPostsLogs200ResponsePagination
        //private ListPostsLogs200ResponsePagination instance;

        public ListPostsLogs200ResponsePaginationTests()
        {
            // TODO uncomment below to create an instance of ListPostsLogs200ResponsePagination
            //instance = new ListPostsLogs200ResponsePagination();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListPostsLogs200ResponsePagination
        /// </summary>
        [Fact]
        public void ListPostsLogs200ResponsePaginationInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListPostsLogs200ResponsePagination
            //Assert.IsType<ListPostsLogs200ResponsePagination>(instance);
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

        /// <summary>
        /// Test the property 'Skip'
        /// </summary>
        [Fact]
        public void SkipTest()
        {
            // TODO unit test for the property 'Skip'
        }

        /// <summary>
        /// Test the property 'Pages'
        /// </summary>
        [Fact]
        public void PagesTest()
        {
            // TODO unit test for the property 'Pages'
        }

        /// <summary>
        /// Test the property 'HasMore'
        /// </summary>
        [Fact]
        public void HasMoreTest()
        {
            // TODO unit test for the property 'HasMore'
        }
    }
}
