/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing ListPostsLogs200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListPostsLogs200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListPostsLogs200Response
        //private ListPostsLogs200Response instance;

        public ListPostsLogs200ResponseTests()
        {
            // TODO uncomment below to create an instance of ListPostsLogs200Response
            //instance = new ListPostsLogs200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListPostsLogs200Response
        /// </summary>
        [Fact]
        public void ListPostsLogs200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListPostsLogs200Response
            //Assert.IsType<ListPostsLogs200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Logs'
        /// </summary>
        [Fact]
        public void LogsTest()
        {
            // TODO unit test for the property 'Logs'
        }

        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }
    }
}
