/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing ProfileDeleteResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProfileDeleteResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProfileDeleteResponse
        //private ProfileDeleteResponse instance;

        public ProfileDeleteResponseTests()
        {
            // TODO uncomment below to create an instance of ProfileDeleteResponse
            //instance = new ProfileDeleteResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProfileDeleteResponse
        /// </summary>
        [Fact]
        public void ProfileDeleteResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProfileDeleteResponse
            //Assert.IsType<ProfileDeleteResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
