/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing RedditPlatformData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RedditPlatformDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RedditPlatformData
        //private RedditPlatformData instance;

        public RedditPlatformDataTests()
        {
            // TODO uncomment below to create an instance of RedditPlatformData
            //instance = new RedditPlatformData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RedditPlatformData
        /// </summary>
        [Fact]
        public void RedditPlatformDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" RedditPlatformData
            //Assert.IsType<RedditPlatformData>(instance);
        }

        /// <summary>
        /// Test the property 'Subreddit'
        /// </summary>
        [Fact]
        public void SubredditTest()
        {
            // TODO unit test for the property 'Subreddit'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'ForceSelf'
        /// </summary>
        [Fact]
        public void ForceSelfTest()
        {
            // TODO unit test for the property 'ForceSelf'
        }
    }
}
