/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing RequestWhatsAppVerificationCode200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RequestWhatsAppVerificationCode200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RequestWhatsAppVerificationCode200Response
        //private RequestWhatsAppVerificationCode200Response instance;

        public RequestWhatsAppVerificationCode200ResponseTests()
        {
            // TODO uncomment below to create an instance of RequestWhatsAppVerificationCode200Response
            //instance = new RequestWhatsAppVerificationCode200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RequestWhatsAppVerificationCode200Response
        /// </summary>
        [Fact]
        public void RequestWhatsAppVerificationCode200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RequestWhatsAppVerificationCode200Response
            //Assert.IsType<RequestWhatsAppVerificationCode200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
    }
}
