/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing ScheduleWhatsAppBroadcastRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScheduleWhatsAppBroadcastRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScheduleWhatsAppBroadcastRequest
        //private ScheduleWhatsAppBroadcastRequest instance;

        public ScheduleWhatsAppBroadcastRequestTests()
        {
            // TODO uncomment below to create an instance of ScheduleWhatsAppBroadcastRequest
            //instance = new ScheduleWhatsAppBroadcastRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScheduleWhatsAppBroadcastRequest
        /// </summary>
        [Fact]
        public void ScheduleWhatsAppBroadcastRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScheduleWhatsAppBroadcastRequest
            //Assert.IsType<ScheduleWhatsAppBroadcastRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ScheduledAt'
        /// </summary>
        [Fact]
        public void ScheduledAtTest()
        {
            // TODO unit test for the property 'ScheduledAt'
        }
    }
}
