/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing SelectLinkedInOrganization200ResponseBulkRefresh
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SelectLinkedInOrganization200ResponseBulkRefreshTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SelectLinkedInOrganization200ResponseBulkRefresh
        //private SelectLinkedInOrganization200ResponseBulkRefresh instance;

        public SelectLinkedInOrganization200ResponseBulkRefreshTests()
        {
            // TODO uncomment below to create an instance of SelectLinkedInOrganization200ResponseBulkRefresh
            //instance = new SelectLinkedInOrganization200ResponseBulkRefresh();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SelectLinkedInOrganization200ResponseBulkRefresh
        /// </summary>
        [Fact]
        public void SelectLinkedInOrganization200ResponseBulkRefreshInstanceTest()
        {
            // TODO uncomment below to test "IsType" SelectLinkedInOrganization200ResponseBulkRefresh
            //Assert.IsType<SelectLinkedInOrganization200ResponseBulkRefresh>(instance);
        }

        /// <summary>
        /// Test the property 'UpdatedCount'
        /// </summary>
        [Fact]
        public void UpdatedCountTest()
        {
            // TODO unit test for the property 'UpdatedCount'
        }

        /// <summary>
        /// Test the property 'Errors'
        /// </summary>
        [Fact]
        public void ErrorsTest()
        {
            // TODO unit test for the property 'Errors'
        }
    }
}
