/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing TestWebhook200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TestWebhook200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TestWebhook200Response
        //private TestWebhook200Response instance;

        public TestWebhook200ResponseTests()
        {
            // TODO uncomment below to create an instance of TestWebhook200Response
            //instance = new TestWebhook200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TestWebhook200Response
        /// </summary>
        [Fact]
        public void TestWebhook200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TestWebhook200Response
            //Assert.IsType<TestWebhook200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
