/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing TwitterPlatformDataThreadItemsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TwitterPlatformDataThreadItemsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TwitterPlatformDataThreadItemsInner
        //private TwitterPlatformDataThreadItemsInner instance;

        public TwitterPlatformDataThreadItemsInnerTests()
        {
            // TODO uncomment below to create an instance of TwitterPlatformDataThreadItemsInner
            //instance = new TwitterPlatformDataThreadItemsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TwitterPlatformDataThreadItemsInner
        /// </summary>
        [Fact]
        public void TwitterPlatformDataThreadItemsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" TwitterPlatformDataThreadItemsInner
            //Assert.IsType<TwitterPlatformDataThreadItemsInner>(instance);
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'MediaItems'
        /// </summary>
        [Fact]
        public void MediaItemsTest()
        {
            // TODO unit test for the property 'MediaItems'
        }
    }
}
