/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInner
        //private UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInner instance;

        public UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInnerTests()
        {
            // TODO uncomment below to create an instance of UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInner
            //instance = new UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInner
        /// </summary>
        [Fact]
        public void UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInner
            //Assert.IsType<UpdateGoogleBusinessLocationDetailsRequestRegularHoursPeriodsInner>(instance);
        }

        /// <summary>
        /// Test the property 'OpenDay'
        /// </summary>
        [Fact]
        public void OpenDayTest()
        {
            // TODO unit test for the property 'OpenDay'
        }

        /// <summary>
        /// Test the property 'OpenTime'
        /// </summary>
        [Fact]
        public void OpenTimeTest()
        {
            // TODO unit test for the property 'OpenTime'
        }

        /// <summary>
        /// Test the property 'CloseDay'
        /// </summary>
        [Fact]
        public void CloseDayTest()
        {
            // TODO unit test for the property 'CloseDay'
        }

        /// <summary>
        /// Test the property 'CloseTime'
        /// </summary>
        [Fact]
        public void CloseTimeTest()
        {
            // TODO unit test for the property 'CloseTime'
        }
    }
}
