/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing ValidatePostLengthRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValidatePostLengthRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ValidatePostLengthRequest
        //private ValidatePostLengthRequest instance;

        public ValidatePostLengthRequestTests()
        {
            // TODO uncomment below to create an instance of ValidatePostLengthRequest
            //instance = new ValidatePostLengthRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ValidatePostLengthRequest
        /// </summary>
        [Fact]
        public void ValidatePostLengthRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ValidatePostLengthRequest
            //Assert.IsType<ValidatePostLengthRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
    }
}
