/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing VerifyWhatsAppPhoneNumberRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VerifyWhatsAppPhoneNumberRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VerifyWhatsAppPhoneNumberRequest
        //private VerifyWhatsAppPhoneNumberRequest instance;

        public VerifyWhatsAppPhoneNumberRequestTests()
        {
            // TODO uncomment below to create an instance of VerifyWhatsAppPhoneNumberRequest
            //instance = new VerifyWhatsAppPhoneNumberRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VerifyWhatsAppPhoneNumberRequest
        /// </summary>
        [Fact]
        public void VerifyWhatsAppPhoneNumberRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" VerifyWhatsAppPhoneNumberRequest
            //Assert.IsType<VerifyWhatsAppPhoneNumberRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
    }
}
