/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookPayloadMessageMessageSender
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookPayloadMessageMessageSenderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookPayloadMessageMessageSender
        //private WebhookPayloadMessageMessageSender instance;

        public WebhookPayloadMessageMessageSenderTests()
        {
            // TODO uncomment below to create an instance of WebhookPayloadMessageMessageSender
            //instance = new WebhookPayloadMessageMessageSender();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookPayloadMessageMessageSender
        /// </summary>
        [Fact]
        public void WebhookPayloadMessageMessageSenderInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookPayloadMessageMessageSender
            //Assert.IsType<WebhookPayloadMessageMessageSender>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Picture'
        /// </summary>
        [Fact]
        public void PictureTest()
        {
            // TODO unit test for the property 'Picture'
        }
    }
}
