/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Late.Model;
using Late.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Late.Test.Model
{
    /// <summary>
    ///  Class for testing WebhookPayloadMessageConversation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WebhookPayloadMessageConversationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WebhookPayloadMessageConversation
        //private WebhookPayloadMessageConversation instance;

        public WebhookPayloadMessageConversationTests()
        {
            // TODO uncomment below to create an instance of WebhookPayloadMessageConversation
            //instance = new WebhookPayloadMessageConversation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WebhookPayloadMessageConversation
        /// </summary>
        [Fact]
        public void WebhookPayloadMessageConversationInstanceTest()
        {
            // TODO uncomment below to test "IsType" WebhookPayloadMessageConversation
            //Assert.IsType<WebhookPayloadMessageConversation>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'PlatformConversationId'
        /// </summary>
        [Fact]
        public void PlatformConversationIdTest()
        {
            // TODO unit test for the property 'PlatformConversationId'
        }

        /// <summary>
        /// Test the property 'ParticipantId'
        /// </summary>
        [Fact]
        public void ParticipantIdTest()
        {
            // TODO unit test for the property 'ParticipantId'
        }

        /// <summary>
        /// Test the property 'ParticipantName'
        /// </summary>
        [Fact]
        public void ParticipantNameTest()
        {
            // TODO unit test for the property 'ParticipantName'
        }

        /// <summary>
        /// Test the property 'ParticipantUsername'
        /// </summary>
        [Fact]
        public void ParticipantUsernameTest()
        {
            // TODO unit test for the property 'ParticipantUsername'
        }

        /// <summary>
        /// Test the property 'ParticipantPicture'
        /// </summary>
        [Fact]
        public void ParticipantPictureTest()
        {
            // TODO unit test for the property 'ParticipantPicture'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
