/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// Bluesky post settings: - Supports text posts with up to 4 images per post - Videos supported (single video per post) - threadItems creates a reply chain (Bluesky thread) - Images exceeding Bluesky&#39;s 1MB limit are automatically compressed - Alt text for images is supported via mediaItem properties 
    /// </summary>
    [DataContract(Name = "BlueskyPlatformData")]
    public partial class BlueskyPlatformData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BlueskyPlatformData" /> class.
        /// </summary>
        /// <param name="threadItems">Sequence of posts in a Bluesky thread (root then replies in order)..</param>
        public BlueskyPlatformData(List<TwitterPlatformDataThreadItemsInner> threadItems = default)
        {
            this.ThreadItems = threadItems;
        }

        /// <summary>
        /// Sequence of posts in a Bluesky thread (root then replies in order).
        /// </summary>
        /// <value>Sequence of posts in a Bluesky thread (root then replies in order).</value>
        [DataMember(Name = "threadItems", EmitDefaultValue = false)]
        public List<TwitterPlatformDataThreadItemsInner> ThreadItems { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BlueskyPlatformData {\n");
            sb.Append("  ThreadItems: ").Append(ThreadItems).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
