/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// BulkUpdateWhatsAppContacts200Response
    /// </summary>
    [DataContract(Name = "bulkUpdateWhatsAppContacts_200_response")]
    public partial class BulkUpdateWhatsAppContacts200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BulkUpdateWhatsAppContacts200Response" /> class.
        /// </summary>
        /// <param name="success">success.</param>
        /// <param name="action">action.</param>
        /// <param name="modified">Number of contacts modified.</param>
        /// <param name="matched">Number of contacts matched.</param>
        public BulkUpdateWhatsAppContacts200Response(bool success = default, string action = default, int modified = default, int matched = default)
        {
            this.Success = success;
            this.Action = action;
            this.Modified = modified;
            this.Matched = matched;
        }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "success", EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets Action
        /// </summary>
        [DataMember(Name = "action", EmitDefaultValue = false)]
        public string Action { get; set; }

        /// <summary>
        /// Number of contacts modified
        /// </summary>
        /// <value>Number of contacts modified</value>
        [DataMember(Name = "modified", EmitDefaultValue = false)]
        public int Modified { get; set; }

        /// <summary>
        /// Number of contacts matched
        /// </summary>
        /// <value>Number of contacts matched</value>
        [DataMember(Name = "matched", EmitDefaultValue = false)]
        public int Matched { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BulkUpdateWhatsAppContacts200Response {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Action: ").Append(Action).Append("\n");
            sb.Append("  Modified: ").Append(Modified).Append("\n");
            sb.Append("  Matched: ").Append(Matched).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
