/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// CheckInstagramHashtags200ResponseResultsInner
    /// </summary>
    [DataContract(Name = "checkInstagramHashtags_200_response_results_inner")]
    public partial class CheckInstagramHashtags200ResponseResultsInner : IValidatableObject
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Banned for value: banned
            /// </summary>
            [EnumMember(Value = "banned")]
            Banned = 1,

            /// <summary>
            /// Enum Restricted for value: restricted
            /// </summary>
            [EnumMember(Value = "restricted")]
            Restricted = 2,

            /// <summary>
            /// Enum Safe for value: safe
            /// </summary>
            [EnumMember(Value = "safe")]
            Safe = 3,

            /// <summary>
            /// Enum Unknown for value: unknown
            /// </summary>
            [EnumMember(Value = "unknown")]
            Unknown = 4
        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CheckInstagramHashtags200ResponseResultsInner" /> class.
        /// </summary>
        /// <param name="hashtag">hashtag.</param>
        /// <param name="status">status.</param>
        /// <param name="reason">reason.</param>
        /// <param name="confidence">confidence.</param>
        public CheckInstagramHashtags200ResponseResultsInner(string hashtag = default, StatusEnum? status = default, string reason = default, decimal confidence = default)
        {
            this.Hashtag = hashtag;
            this.Status = status;
            this.Reason = reason;
            this.Confidence = confidence;
        }

        /// <summary>
        /// Gets or Sets Hashtag
        /// </summary>
        [DataMember(Name = "hashtag", EmitDefaultValue = false)]
        public string Hashtag { get; set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [DataMember(Name = "reason", EmitDefaultValue = false)]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or Sets Confidence
        /// </summary>
        [DataMember(Name = "confidence", EmitDefaultValue = false)]
        public decimal Confidence { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CheckInstagramHashtags200ResponseResultsInner {\n");
            sb.Append("  Hashtag: ").Append(Hashtag).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Confidence: ").Append(Confidence).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
