/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// Success details (present on successful events)
    /// </summary>
    [DataContract(Name = "ConnectionLog_success")]
    public partial class ConnectionLogSuccess : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionLogSuccess" /> class.
        /// </summary>
        /// <param name="displayName">displayName.</param>
        /// <param name="username">username.</param>
        /// <param name="profilePicture">profilePicture.</param>
        /// <param name="permissions">OAuth scopes/permissions granted.</param>
        /// <param name="tokenExpiresAt">tokenExpiresAt.</param>
        /// <param name="accountType">Account type (personal, business, organization).</param>
        public ConnectionLogSuccess(string displayName = default, string username = default, string profilePicture = default, List<string> permissions = default, DateTime tokenExpiresAt = default, string accountType = default)
        {
            this.DisplayName = displayName;
            this.Username = username;
            this.ProfilePicture = profilePicture;
            this.Permissions = permissions;
            this.TokenExpiresAt = tokenExpiresAt;
            this.AccountType = accountType;
        }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [DataMember(Name = "displayName", EmitDefaultValue = false)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [DataMember(Name = "username", EmitDefaultValue = false)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or Sets ProfilePicture
        /// </summary>
        [DataMember(Name = "profilePicture", EmitDefaultValue = false)]
        public string ProfilePicture { get; set; }

        /// <summary>
        /// OAuth scopes/permissions granted
        /// </summary>
        /// <value>OAuth scopes/permissions granted</value>
        [DataMember(Name = "permissions", EmitDefaultValue = false)]
        public List<string> Permissions { get; set; }

        /// <summary>
        /// Gets or Sets TokenExpiresAt
        /// </summary>
        [DataMember(Name = "tokenExpiresAt", EmitDefaultValue = false)]
        public DateTime TokenExpiresAt { get; set; }

        /// <summary>
        /// Account type (personal, business, organization)
        /// </summary>
        /// <value>Account type (personal, business, organization)</value>
        [DataMember(Name = "accountType", EmitDefaultValue = false)]
        public string AccountType { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConnectionLogSuccess {\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  ProfilePicture: ").Append(ProfilePicture).Append("\n");
            sb.Append("  Permissions: ").Append(Permissions).Append("\n");
            sb.Append("  TokenExpiresAt: ").Append(TokenExpiresAt).Append("\n");
            sb.Append("  AccountType: ").Append(AccountType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
