/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// Error details (present on failed events)
    /// </summary>
    [DataContract(Name = "ConnectionLog_error")]
    public partial class ConnectionLogError : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ConnectionLogError" /> class.
        /// </summary>
        /// <param name="code">Error code (e.g., oauth_denied, token_exchange_failed).</param>
        /// <param name="message">Human-readable error message.</param>
        /// <param name="rawResponse">Raw error response (truncated to 2000 chars).</param>
        public ConnectionLogError(string code = default, string message = default, string rawResponse = default)
        {
            this.Code = code;
            this.Message = message;
            this.RawResponse = rawResponse;
        }

        /// <summary>
        /// Error code (e.g., oauth_denied, token_exchange_failed)
        /// </summary>
        /// <value>Error code (e.g., oauth_denied, token_exchange_failed)</value>
        [DataMember(Name = "code", EmitDefaultValue = false)]
        public string Code { get; set; }

        /// <summary>
        /// Human-readable error message
        /// </summary>
        /// <value>Human-readable error message</value>
        [DataMember(Name = "message", EmitDefaultValue = false)]
        public string Message { get; set; }

        /// <summary>
        /// Raw error response (truncated to 2000 chars)
        /// </summary>
        /// <value>Raw error response (truncated to 2000 chars)</value>
        [DataMember(Name = "rawResponse", EmitDefaultValue = false)]
        public string RawResponse { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConnectionLogError {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  RawResponse: ").Append(RawResponse).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
