/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// CreateStandaloneAdRequest
    /// </summary>
    [DataContract(Name = "createStandaloneAd_request")]
    public partial class CreateStandaloneAdRequest : IValidatableObject
    {
        /// <summary>
        /// Available goals vary by platform. Meta (Facebook/Instagram) and TikTok support all 7. LinkedIn supports all except app_promotion. Twitter/X supports engagement, traffic, awareness, video_views, app_promotion. Pinterest and Google Ads support only engagement, traffic, awareness, video_views.
        /// </summary>
        /// <value>Available goals vary by platform. Meta (Facebook/Instagram) and TikTok support all 7. LinkedIn supports all except app_promotion. Twitter/X supports engagement, traffic, awareness, video_views, app_promotion. Pinterest and Google Ads support only engagement, traffic, awareness, video_views.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum GoalEnum
        {
            /// <summary>
            /// Enum Engagement for value: engagement
            /// </summary>
            [EnumMember(Value = "engagement")]
            Engagement = 1,

            /// <summary>
            /// Enum Traffic for value: traffic
            /// </summary>
            [EnumMember(Value = "traffic")]
            Traffic = 2,

            /// <summary>
            /// Enum Awareness for value: awareness
            /// </summary>
            [EnumMember(Value = "awareness")]
            Awareness = 3,

            /// <summary>
            /// Enum VideoViews for value: video_views
            /// </summary>
            [EnumMember(Value = "video_views")]
            VideoViews = 4,

            /// <summary>
            /// Enum LeadGeneration for value: lead_generation
            /// </summary>
            [EnumMember(Value = "lead_generation")]
            LeadGeneration = 5,

            /// <summary>
            /// Enum Conversions for value: conversions
            /// </summary>
            [EnumMember(Value = "conversions")]
            Conversions = 6,

            /// <summary>
            /// Enum AppPromotion for value: app_promotion
            /// </summary>
            [EnumMember(Value = "app_promotion")]
            AppPromotion = 7
        }


        /// <summary>
        /// Available goals vary by platform. Meta (Facebook/Instagram) and TikTok support all 7. LinkedIn supports all except app_promotion. Twitter/X supports engagement, traffic, awareness, video_views, app_promotion. Pinterest and Google Ads support only engagement, traffic, awareness, video_views.
        /// </summary>
        /// <value>Available goals vary by platform. Meta (Facebook/Instagram) and TikTok support all 7. LinkedIn supports all except app_promotion. Twitter/X supports engagement, traffic, awareness, video_views, app_promotion. Pinterest and Google Ads support only engagement, traffic, awareness, video_views.</value>
        [DataMember(Name = "goal", IsRequired = true, EmitDefaultValue = true)]
        public GoalEnum Goal { get; set; }
        /// <summary>
        /// Defines BudgetType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum BudgetTypeEnum
        {
            /// <summary>
            /// Enum Daily for value: daily
            /// </summary>
            [EnumMember(Value = "daily")]
            Daily = 1,

            /// <summary>
            /// Enum Lifetime for value: lifetime
            /// </summary>
            [EnumMember(Value = "lifetime")]
            Lifetime = 2
        }


        /// <summary>
        /// Gets or Sets BudgetType
        /// </summary>
        [DataMember(Name = "budgetType", IsRequired = true, EmitDefaultValue = true)]
        public BudgetTypeEnum BudgetType { get; set; }
        /// <summary>
        /// Meta only
        /// </summary>
        /// <value>Meta only</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CallToActionEnum
        {
            /// <summary>
            /// Enum LEARNMORE for value: LEARN_MORE
            /// </summary>
            [EnumMember(Value = "LEARN_MORE")]
            LEARNMORE = 1,

            /// <summary>
            /// Enum SHOPNOW for value: SHOP_NOW
            /// </summary>
            [EnumMember(Value = "SHOP_NOW")]
            SHOPNOW = 2,

            /// <summary>
            /// Enum SIGNUP for value: SIGN_UP
            /// </summary>
            [EnumMember(Value = "SIGN_UP")]
            SIGNUP = 3,

            /// <summary>
            /// Enum BOOKTRAVEL for value: BOOK_TRAVEL
            /// </summary>
            [EnumMember(Value = "BOOK_TRAVEL")]
            BOOKTRAVEL = 4,

            /// <summary>
            /// Enum CONTACTUS for value: CONTACT_US
            /// </summary>
            [EnumMember(Value = "CONTACT_US")]
            CONTACTUS = 5,

            /// <summary>
            /// Enum DOWNLOAD for value: DOWNLOAD
            /// </summary>
            [EnumMember(Value = "DOWNLOAD")]
            DOWNLOAD = 6,

            /// <summary>
            /// Enum GETOFFER for value: GET_OFFER
            /// </summary>
            [EnumMember(Value = "GET_OFFER")]
            GETOFFER = 7,

            /// <summary>
            /// Enum GETQUOTE for value: GET_QUOTE
            /// </summary>
            [EnumMember(Value = "GET_QUOTE")]
            GETQUOTE = 8,

            /// <summary>
            /// Enum SUBSCRIBE for value: SUBSCRIBE
            /// </summary>
            [EnumMember(Value = "SUBSCRIBE")]
            SUBSCRIBE = 9,

            /// <summary>
            /// Enum WATCHMORE for value: WATCH_MORE
            /// </summary>
            [EnumMember(Value = "WATCH_MORE")]
            WATCHMORE = 10
        }


        /// <summary>
        /// Meta only
        /// </summary>
        /// <value>Meta only</value>
        [DataMember(Name = "callToAction", EmitDefaultValue = false)]
        public CallToActionEnum? CallToAction { get; set; }
        /// <summary>
        /// Google only
        /// </summary>
        /// <value>Google only</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CampaignTypeEnum
        {
            /// <summary>
            /// Enum Display for value: display
            /// </summary>
            [EnumMember(Value = "display")]
            Display = 1,

            /// <summary>
            /// Enum Search for value: search
            /// </summary>
            [EnumMember(Value = "search")]
            Search = 2
        }


        /// <summary>
        /// Google only
        /// </summary>
        /// <value>Google only</value>
        [DataMember(Name = "campaignType", EmitDefaultValue = false)]
        public CampaignTypeEnum? CampaignType { get; set; }
        /// <summary>
        /// Meta only. Controls the Advantage audience feature (targeting_automation). 0 &#x3D; disabled (default), 1 &#x3D; enabled. Meta Marketing API requires this field on all ad set creation requests.
        /// </summary>
        /// <value>Meta only. Controls the Advantage audience feature (targeting_automation). 0 &#x3D; disabled (default), 1 &#x3D; enabled. Meta Marketing API requires this field on all ad set creation requests.</value>
        public enum AdvantageAudienceEnum
        {
            /// <summary>
            /// Enum NUMBER_0 for value: 0
            /// </summary>
            NUMBER_0 = 0,

            /// <summary>
            /// Enum NUMBER_1 for value: 1
            /// </summary>
            NUMBER_1 = 1
        }


        /// <summary>
        /// Meta only. Controls the Advantage audience feature (targeting_automation). 0 &#x3D; disabled (default), 1 &#x3D; enabled. Meta Marketing API requires this field on all ad set creation requests.
        /// </summary>
        /// <value>Meta only. Controls the Advantage audience feature (targeting_automation). 0 &#x3D; disabled (default), 1 &#x3D; enabled. Meta Marketing API requires this field on all ad set creation requests.</value>
        [DataMember(Name = "advantageAudience", EmitDefaultValue = false)]
        public AdvantageAudienceEnum? AdvantageAudience { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateStandaloneAdRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateStandaloneAdRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateStandaloneAdRequest" /> class.
        /// </summary>
        /// <param name="accountId">accountId (required).</param>
        /// <param name="adAccountId">adAccountId (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="goal">Available goals vary by platform. Meta (Facebook/Instagram) and TikTok support all 7. LinkedIn supports all except app_promotion. Twitter/X supports engagement, traffic, awareness, video_views, app_promotion. Pinterest and Google Ads support only engagement, traffic, awareness, video_views. (required).</param>
        /// <param name="budgetAmount">budgetAmount (required).</param>
        /// <param name="budgetType">budgetType (required).</param>
        /// <param name="currency">currency.</param>
        /// <param name="headline">Required for most platforms. Max: Meta&#x3D;255, Google&#x3D;30, Pinterest&#x3D;100.</param>
        /// <param name="longHeadline">Google Display only.</param>
        /// <param name="body">Max: Google&#x3D;90, Pinterest&#x3D;500 (required).</param>
        /// <param name="callToAction">Meta only.</param>
        /// <param name="linkUrl">linkUrl.</param>
        /// <param name="imageUrl">Image URL (or video URL for TikTok). Not required for Google Search campaigns..</param>
        /// <param name="businessName">Google Display only.</param>
        /// <param name="boardId">Pinterest only. Board ID (auto-creates if not provided)..</param>
        /// <param name="countries">countries.</param>
        /// <param name="ageMin">ageMin.</param>
        /// <param name="ageMax">ageMax.</param>
        /// <param name="interests">Interest objects from /v1/ads/interests. Each must include id and name..</param>
        /// <param name="endDate">Required for lifetime budgets.</param>
        /// <param name="audienceId">Custom audience ID for targeting.</param>
        /// <param name="campaignType">Google only (default to CampaignTypeEnum.Display).</param>
        /// <param name="keywords">Google Search only.</param>
        /// <param name="additionalHeadlines">Google Search RSA only. Extra headlines..</param>
        /// <param name="additionalDescriptions">Google Search RSA only. Extra descriptions..</param>
        /// <param name="advantageAudience">Meta only. Controls the Advantage audience feature (targeting_automation). 0 &#x3D; disabled (default), 1 &#x3D; enabled. Meta Marketing API requires this field on all ad set creation requests..</param>
        public CreateStandaloneAdRequest(string accountId = default, string adAccountId = default, string name = default, GoalEnum goal = default, decimal budgetAmount = default, BudgetTypeEnum budgetType = default, string currency = default, string headline = default, string longHeadline = default, string body = default, CallToActionEnum? callToAction = default, string linkUrl = default, string imageUrl = default, string businessName = default, string boardId = default, List<string> countries = default, int ageMin = default, int ageMax = default, List<UpdateAdRequestTargetingInterestsInner> interests = default, DateTime endDate = default, string audienceId = default, CampaignTypeEnum? campaignType = CampaignTypeEnum.Display, List<string> keywords = default, List<string> additionalHeadlines = default, List<string> additionalDescriptions = default, AdvantageAudienceEnum? advantageAudience = default)
        {
            // to ensure "accountId" is required (not null)
            if (accountId == null)
            {
                throw new ArgumentNullException("accountId is a required property for CreateStandaloneAdRequest and cannot be null");
            }
            this.AccountId = accountId;
            // to ensure "adAccountId" is required (not null)
            if (adAccountId == null)
            {
                throw new ArgumentNullException("adAccountId is a required property for CreateStandaloneAdRequest and cannot be null");
            }
            this.AdAccountId = adAccountId;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for CreateStandaloneAdRequest and cannot be null");
            }
            this.Name = name;
            this.Goal = goal;
            this.BudgetAmount = budgetAmount;
            this.BudgetType = budgetType;
            // to ensure "body" is required (not null)
            if (body == null)
            {
                throw new ArgumentNullException("body is a required property for CreateStandaloneAdRequest and cannot be null");
            }
            this.Body = body;
            this.Currency = currency;
            this.Headline = headline;
            this.LongHeadline = longHeadline;
            this.CallToAction = callToAction;
            this.LinkUrl = linkUrl;
            this.ImageUrl = imageUrl;
            this.BusinessName = businessName;
            this.BoardId = boardId;
            this.Countries = countries;
            this.AgeMin = ageMin;
            this.AgeMax = ageMax;
            this.Interests = interests;
            this.EndDate = endDate;
            this.AudienceId = audienceId;
            this.CampaignType = campaignType;
            this.Keywords = keywords;
            this.AdditionalHeadlines = additionalHeadlines;
            this.AdditionalDescriptions = additionalDescriptions;
            this.AdvantageAudience = advantageAudience;
        }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name = "accountId", IsRequired = true, EmitDefaultValue = true)]
        public string AccountId { get; set; }

        /// <summary>
        /// Gets or Sets AdAccountId
        /// </summary>
        [DataMember(Name = "adAccountId", IsRequired = true, EmitDefaultValue = true)]
        public string AdAccountId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets BudgetAmount
        /// </summary>
        [DataMember(Name = "budgetAmount", IsRequired = true, EmitDefaultValue = true)]
        public decimal BudgetAmount { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", EmitDefaultValue = false)]
        public string Currency { get; set; }

        /// <summary>
        /// Required for most platforms. Max: Meta&#x3D;255, Google&#x3D;30, Pinterest&#x3D;100
        /// </summary>
        /// <value>Required for most platforms. Max: Meta&#x3D;255, Google&#x3D;30, Pinterest&#x3D;100</value>
        [DataMember(Name = "headline", EmitDefaultValue = false)]
        public string Headline { get; set; }

        /// <summary>
        /// Google Display only
        /// </summary>
        /// <value>Google Display only</value>
        [DataMember(Name = "longHeadline", EmitDefaultValue = false)]
        public string LongHeadline { get; set; }

        /// <summary>
        /// Max: Google&#x3D;90, Pinterest&#x3D;500
        /// </summary>
        /// <value>Max: Google&#x3D;90, Pinterest&#x3D;500</value>
        [DataMember(Name = "body", IsRequired = true, EmitDefaultValue = true)]
        public string Body { get; set; }

        /// <summary>
        /// Gets or Sets LinkUrl
        /// </summary>
        [DataMember(Name = "linkUrl", EmitDefaultValue = false)]
        public string LinkUrl { get; set; }

        /// <summary>
        /// Image URL (or video URL for TikTok). Not required for Google Search campaigns.
        /// </summary>
        /// <value>Image URL (or video URL for TikTok). Not required for Google Search campaigns.</value>
        [DataMember(Name = "imageUrl", EmitDefaultValue = false)]
        public string ImageUrl { get; set; }

        /// <summary>
        /// Google Display only
        /// </summary>
        /// <value>Google Display only</value>
        [DataMember(Name = "businessName", EmitDefaultValue = false)]
        public string BusinessName { get; set; }

        /// <summary>
        /// Pinterest only. Board ID (auto-creates if not provided).
        /// </summary>
        /// <value>Pinterest only. Board ID (auto-creates if not provided).</value>
        [DataMember(Name = "boardId", EmitDefaultValue = false)]
        public string BoardId { get; set; }

        /// <summary>
        /// Gets or Sets Countries
        /// </summary>
        [DataMember(Name = "countries", EmitDefaultValue = false)]
        public List<string> Countries { get; set; }

        /// <summary>
        /// Gets or Sets AgeMin
        /// </summary>
        [DataMember(Name = "ageMin", EmitDefaultValue = false)]
        public int AgeMin { get; set; }

        /// <summary>
        /// Gets or Sets AgeMax
        /// </summary>
        [DataMember(Name = "ageMax", EmitDefaultValue = false)]
        public int AgeMax { get; set; }

        /// <summary>
        /// Interest objects from /v1/ads/interests. Each must include id and name.
        /// </summary>
        /// <value>Interest objects from /v1/ads/interests. Each must include id and name.</value>
        [DataMember(Name = "interests", EmitDefaultValue = false)]
        public List<UpdateAdRequestTargetingInterestsInner> Interests { get; set; }

        /// <summary>
        /// Required for lifetime budgets
        /// </summary>
        /// <value>Required for lifetime budgets</value>
        [DataMember(Name = "endDate", EmitDefaultValue = false)]
        public DateTime EndDate { get; set; }

        /// <summary>
        /// Custom audience ID for targeting
        /// </summary>
        /// <value>Custom audience ID for targeting</value>
        [DataMember(Name = "audienceId", EmitDefaultValue = false)]
        public string AudienceId { get; set; }

        /// <summary>
        /// Google Search only
        /// </summary>
        /// <value>Google Search only</value>
        [DataMember(Name = "keywords", EmitDefaultValue = false)]
        public List<string> Keywords { get; set; }

        /// <summary>
        /// Google Search RSA only. Extra headlines.
        /// </summary>
        /// <value>Google Search RSA only. Extra headlines.</value>
        [DataMember(Name = "additionalHeadlines", EmitDefaultValue = false)]
        public List<string> AdditionalHeadlines { get; set; }

        /// <summary>
        /// Google Search RSA only. Extra descriptions.
        /// </summary>
        /// <value>Google Search RSA only. Extra descriptions.</value>
        [DataMember(Name = "additionalDescriptions", EmitDefaultValue = false)]
        public List<string> AdditionalDescriptions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateStandaloneAdRequest {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  AdAccountId: ").Append(AdAccountId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Goal: ").Append(Goal).Append("\n");
            sb.Append("  BudgetAmount: ").Append(BudgetAmount).Append("\n");
            sb.Append("  BudgetType: ").Append(BudgetType).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Headline: ").Append(Headline).Append("\n");
            sb.Append("  LongHeadline: ").Append(LongHeadline).Append("\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  CallToAction: ").Append(CallToAction).Append("\n");
            sb.Append("  LinkUrl: ").Append(LinkUrl).Append("\n");
            sb.Append("  ImageUrl: ").Append(ImageUrl).Append("\n");
            sb.Append("  BusinessName: ").Append(BusinessName).Append("\n");
            sb.Append("  BoardId: ").Append(BoardId).Append("\n");
            sb.Append("  Countries: ").Append(Countries).Append("\n");
            sb.Append("  AgeMin: ").Append(AgeMin).Append("\n");
            sb.Append("  AgeMax: ").Append(AgeMax).Append("\n");
            sb.Append("  Interests: ").Append(Interests).Append("\n");
            sb.Append("  EndDate: ").Append(EndDate).Append("\n");
            sb.Append("  AudienceId: ").Append(AudienceId).Append("\n");
            sb.Append("  CampaignType: ").Append(CampaignType).Append("\n");
            sb.Append("  Keywords: ").Append(Keywords).Append("\n");
            sb.Append("  AdditionalHeadlines: ").Append(AdditionalHeadlines).Append("\n");
            sb.Append("  AdditionalDescriptions: ").Append(AdditionalDescriptions).Append("\n");
            sb.Append("  AdvantageAudience: ").Append(AdvantageAudience).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 255)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 255.", new [] { "Name" });
            }

            // LongHeadline (string) maxLength
            if (this.LongHeadline != null && this.LongHeadline.Length > 90)
            {
                yield return new ValidationResult("Invalid value for LongHeadline, length must be less than 90.", new [] { "LongHeadline" });
            }

            // BusinessName (string) maxLength
            if (this.BusinessName != null && this.BusinessName.Length > 25)
            {
                yield return new ValidationResult("Invalid value for BusinessName, length must be less than 25.", new [] { "BusinessName" });
            }

            // AgeMin (int) maximum
            if (this.AgeMin > (int)65)
            {
                yield return new ValidationResult("Invalid value for AgeMin, must be a value less than or equal to 65.", new [] { "AgeMin" });
            }

            // AgeMin (int) minimum
            if (this.AgeMin < (int)13)
            {
                yield return new ValidationResult("Invalid value for AgeMin, must be a value greater than or equal to 13.", new [] { "AgeMin" });
            }

            // AgeMax (int) maximum
            if (this.AgeMax > (int)65)
            {
                yield return new ValidationResult("Invalid value for AgeMax, must be a value less than or equal to 65.", new [] { "AgeMax" });
            }

            // AgeMax (int) minimum
            if (this.AgeMax < (int)13)
            {
                yield return new ValidationResult("Invalid value for AgeMax, must be a value greater than or equal to 13.", new [] { "AgeMax" });
            }

            yield break;
        }
    }

}
