/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// Up to 10 images for feed posts, cannot mix videos and images. Stories require single image or video (ephemeral 24h, no captions). Use pageId for multi-page posting.
    /// </summary>
    [DataContract(Name = "FacebookPlatformData")]
    public partial class FacebookPlatformData : IValidatableObject
    {
        /// <summary>
        /// Set to &#39;story&#39; to publish as a Facebook Page Story (24-hour ephemeral content). Requires media.
        /// </summary>
        /// <value>Set to &#39;story&#39; to publish as a Facebook Page Story (24-hour ephemeral content). Requires media.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ContentTypeEnum
        {
            /// <summary>
            /// Enum Story for value: story
            /// </summary>
            [EnumMember(Value = "story")]
            Story = 1
        }


        /// <summary>
        /// Set to &#39;story&#39; to publish as a Facebook Page Story (24-hour ephemeral content). Requires media.
        /// </summary>
        /// <value>Set to &#39;story&#39; to publish as a Facebook Page Story (24-hour ephemeral content). Requires media.</value>
        [DataMember(Name = "contentType", EmitDefaultValue = false)]
        public ContentTypeEnum? ContentType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FacebookPlatformData" /> class.
        /// </summary>
        /// <param name="contentType">Set to &#39;story&#39; to publish as a Facebook Page Story (24-hour ephemeral content). Requires media..</param>
        /// <param name="firstComment">Optional first comment to post immediately after publishing (feed posts only, not stories).</param>
        /// <param name="pageId">Target Facebook Page ID for multi-page posting. If omitted, uses the default page. Use GET /v1/accounts/{id}/facebook-page to list pages..</param>
        public FacebookPlatformData(ContentTypeEnum? contentType = default, string firstComment = default, string pageId = default)
        {
            this.ContentType = contentType;
            this.FirstComment = firstComment;
            this.PageId = pageId;
        }

        /// <summary>
        /// Optional first comment to post immediately after publishing (feed posts only, not stories)
        /// </summary>
        /// <value>Optional first comment to post immediately after publishing (feed posts only, not stories)</value>
        [DataMember(Name = "firstComment", EmitDefaultValue = false)]
        public string FirstComment { get; set; }

        /// <summary>
        /// Target Facebook Page ID for multi-page posting. If omitted, uses the default page. Use GET /v1/accounts/{id}/facebook-page to list pages.
        /// </summary>
        /// <value>Target Facebook Page ID for multi-page posting. If omitted, uses the default page. Use GET /v1/accounts/{id}/facebook-page to list pages.</value>
        [DataMember(Name = "pageId", EmitDefaultValue = false)]
        public string PageId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FacebookPlatformData {\n");
            sb.Append("  ContentType: ").Append(ContentType).Append("\n");
            sb.Append("  FirstComment: ").Append(FirstComment).Append("\n");
            sb.Append("  PageId: ").Append(PageId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
