/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// GetGoogleBusinessAttributes200ResponseAttributesInnerRepeatedEnumValue
    /// </summary>
    [DataContract(Name = "getGoogleBusinessAttributes_200_response_attributes_inner_repeatedEnumValue")]
    public partial class GetGoogleBusinessAttributes200ResponseAttributesInnerRepeatedEnumValue : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetGoogleBusinessAttributes200ResponseAttributesInnerRepeatedEnumValue" /> class.
        /// </summary>
        /// <param name="setValues">setValues.</param>
        /// <param name="unsetValues">unsetValues.</param>
        public GetGoogleBusinessAttributes200ResponseAttributesInnerRepeatedEnumValue(List<string> setValues = default, List<string> unsetValues = default)
        {
            this.SetValues = setValues;
            this.UnsetValues = unsetValues;
        }

        /// <summary>
        /// Gets or Sets SetValues
        /// </summary>
        [DataMember(Name = "setValues", EmitDefaultValue = false)]
        public List<string> SetValues { get; set; }

        /// <summary>
        /// Gets or Sets UnsetValues
        /// </summary>
        [DataMember(Name = "unsetValues", EmitDefaultValue = false)]
        public List<string> UnsetValues { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetGoogleBusinessAttributes200ResponseAttributesInnerRepeatedEnumValue {\n");
            sb.Append("  SetValues: ").Append(SetValues).Append("\n");
            sb.Append("  UnsetValues: ").Append(UnsetValues).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
