/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// GetInboxConversation200ResponseData
    /// </summary>
    [DataContract(Name = "getInboxConversation_200_response_data")]
    public partial class GetInboxConversation200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Active for value: active
            /// </summary>
            [EnumMember(Value = "active")]
            Active = 1,

            /// <summary>
            /// Enum Archived for value: archived
            /// </summary>
            [EnumMember(Value = "archived")]
            Archived = 2
        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetInboxConversation200ResponseData" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="accountId">accountId.</param>
        /// <param name="accountUsername">accountUsername.</param>
        /// <param name="platform">platform.</param>
        /// <param name="status">status.</param>
        /// <param name="participantName">participantName.</param>
        /// <param name="participantId">participantId.</param>
        /// <param name="lastMessage">lastMessage.</param>
        /// <param name="lastMessageAt">lastMessageAt.</param>
        /// <param name="updatedTime">updatedTime.</param>
        /// <param name="participants">participants.</param>
        public GetInboxConversation200ResponseData(string id = default, string accountId = default, string accountUsername = default, string platform = default, StatusEnum? status = default, string participantName = default, string participantId = default, string lastMessage = default, DateTime lastMessageAt = default, DateTime updatedTime = default, List<UpdateFacebookPage200ResponseSelectedPage> participants = default)
        {
            this.Id = id;
            this.AccountId = accountId;
            this.AccountUsername = accountUsername;
            this.Platform = platform;
            this.Status = status;
            this.ParticipantName = participantName;
            this.ParticipantId = participantId;
            this.LastMessage = lastMessage;
            this.LastMessageAt = lastMessageAt;
            this.UpdatedTime = updatedTime;
            this.Participants = participants;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name = "accountId", EmitDefaultValue = false)]
        public string AccountId { get; set; }

        /// <summary>
        /// Gets or Sets AccountUsername
        /// </summary>
        [DataMember(Name = "accountUsername", EmitDefaultValue = false)]
        public string AccountUsername { get; set; }

        /// <summary>
        /// Gets or Sets Platform
        /// </summary>
        [DataMember(Name = "platform", EmitDefaultValue = false)]
        public string Platform { get; set; }

        /// <summary>
        /// Gets or Sets ParticipantName
        /// </summary>
        [DataMember(Name = "participantName", EmitDefaultValue = false)]
        public string ParticipantName { get; set; }

        /// <summary>
        /// Gets or Sets ParticipantId
        /// </summary>
        [DataMember(Name = "participantId", EmitDefaultValue = false)]
        public string ParticipantId { get; set; }

        /// <summary>
        /// Gets or Sets LastMessage
        /// </summary>
        [DataMember(Name = "lastMessage", EmitDefaultValue = false)]
        public string LastMessage { get; set; }

        /// <summary>
        /// Gets or Sets LastMessageAt
        /// </summary>
        [DataMember(Name = "lastMessageAt", EmitDefaultValue = false)]
        public DateTime LastMessageAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedTime
        /// </summary>
        [DataMember(Name = "updatedTime", EmitDefaultValue = false)]
        public DateTime UpdatedTime { get; set; }

        /// <summary>
        /// Gets or Sets Participants
        /// </summary>
        [DataMember(Name = "participants", EmitDefaultValue = false)]
        public List<UpdateFacebookPage200ResponseSelectedPage> Participants { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetInboxConversation200ResponseData {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  AccountUsername: ").Append(AccountUsername).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  ParticipantName: ").Append(ParticipantName).Append("\n");
            sb.Append("  ParticipantId: ").Append(ParticipantId).Append("\n");
            sb.Append("  LastMessage: ").Append(LastMessage).Append("\n");
            sb.Append("  LastMessageAt: ").Append(LastMessageAt).Append("\n");
            sb.Append("  UpdatedTime: ").Append(UpdatedTime).Append("\n");
            sb.Append("  Participants: ").Append(Participants).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
