/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// GetPreverifiedWhatsAppNumbers200ResponseNumbersInner
    /// </summary>
    [DataContract(Name = "getPreverifiedWhatsAppNumbers_200_response_numbers_inner")]
    public partial class GetPreverifiedWhatsAppNumbers200ResponseNumbersInner : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetPreverifiedWhatsAppNumbers200ResponseNumbersInner" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="phoneNumber">phoneNumber.</param>
        /// <param name="metaPreverifiedId">metaPreverifiedId.</param>
        /// <param name="metaVerifiedAt">metaVerifiedAt.</param>
        /// <param name="metaVerificationExpiresAt">metaVerificationExpiresAt.</param>
        public GetPreverifiedWhatsAppNumbers200ResponseNumbersInner(string id = default, string phoneNumber = default, string metaPreverifiedId = default, DateTime metaVerifiedAt = default, DateTime metaVerificationExpiresAt = default)
        {
            this.Id = id;
            this.PhoneNumber = phoneNumber;
            this.MetaPreverifiedId = metaPreverifiedId;
            this.MetaVerifiedAt = metaVerifiedAt;
            this.MetaVerificationExpiresAt = metaVerificationExpiresAt;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets PhoneNumber
        /// </summary>
        [DataMember(Name = "phoneNumber", EmitDefaultValue = false)]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Gets or Sets MetaPreverifiedId
        /// </summary>
        [DataMember(Name = "metaPreverifiedId", EmitDefaultValue = false)]
        public string MetaPreverifiedId { get; set; }

        /// <summary>
        /// Gets or Sets MetaVerifiedAt
        /// </summary>
        [DataMember(Name = "metaVerifiedAt", EmitDefaultValue = false)]
        public DateTime MetaVerifiedAt { get; set; }

        /// <summary>
        /// Gets or Sets MetaVerificationExpiresAt
        /// </summary>
        [DataMember(Name = "metaVerificationExpiresAt", EmitDefaultValue = false)]
        public DateTime MetaVerificationExpiresAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetPreverifiedWhatsAppNumbers200ResponseNumbersInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PhoneNumber: ").Append(PhoneNumber).Append("\n");
            sb.Append("  MetaPreverifiedId: ").Append(MetaPreverifiedId).Append("\n");
            sb.Append("  MetaVerifiedAt: ").Append(MetaVerifiedAt).Append("\n");
            sb.Append("  MetaVerificationExpiresAt: ").Append(MetaVerificationExpiresAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
