/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// GetWhatsAppBroadcastRecipients200Response
    /// </summary>
    [DataContract(Name = "getWhatsAppBroadcastRecipients_200_response")]
    public partial class GetWhatsAppBroadcastRecipients200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetWhatsAppBroadcastRecipients200Response" /> class.
        /// </summary>
        /// <param name="success">success.</param>
        /// <param name="recipients">recipients.</param>
        /// <param name="pagination">pagination.</param>
        /// <param name="summary">summary.</param>
        public GetWhatsAppBroadcastRecipients200Response(bool success = default, List<GetWhatsAppBroadcastRecipients200ResponseRecipientsInner> recipients = default, GetWhatsAppContacts200ResponsePagination pagination = default, GetWhatsAppBroadcastRecipients200ResponseSummary summary = default)
        {
            this.Success = success;
            this.Recipients = recipients;
            this.Pagination = pagination;
            this.Summary = summary;
        }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "success", EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets Recipients
        /// </summary>
        [DataMember(Name = "recipients", EmitDefaultValue = false)]
        public List<GetWhatsAppBroadcastRecipients200ResponseRecipientsInner> Recipients { get; set; }

        /// <summary>
        /// Gets or Sets Pagination
        /// </summary>
        [DataMember(Name = "pagination", EmitDefaultValue = false)]
        public GetWhatsAppContacts200ResponsePagination Pagination { get; set; }

        /// <summary>
        /// Gets or Sets Summary
        /// </summary>
        [DataMember(Name = "summary", EmitDefaultValue = false)]
        public GetWhatsAppBroadcastRecipients200ResponseSummary Summary { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetWhatsAppBroadcastRecipients200Response {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Recipients: ").Append(Recipients).Append("\n");
            sb.Append("  Pagination: ").Append(Pagination).Append("\n");
            sb.Append("  Summary: ").Append(Summary).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
