/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// GetYouTubeTranscript200Response
    /// </summary>
    [DataContract(Name = "getYouTubeTranscript_200_response")]
    public partial class GetYouTubeTranscript200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetYouTubeTranscript200Response" /> class.
        /// </summary>
        /// <param name="success">success.</param>
        /// <param name="videoId">videoId.</param>
        /// <param name="language">language.</param>
        /// <param name="fullText">fullText.</param>
        /// <param name="segments">segments.</param>
        public GetYouTubeTranscript200Response(bool success = default, string videoId = default, string language = default, string fullText = default, List<GetYouTubeTranscript200ResponseSegmentsInner> segments = default)
        {
            this.Success = success;
            this.VideoId = videoId;
            this.Language = language;
            this.FullText = fullText;
            this.Segments = segments;
        }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "success", EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets VideoId
        /// </summary>
        [DataMember(Name = "videoId", EmitDefaultValue = false)]
        public string VideoId { get; set; }

        /// <summary>
        /// Gets or Sets Language
        /// </summary>
        [DataMember(Name = "language", EmitDefaultValue = false)]
        public string Language { get; set; }

        /// <summary>
        /// Gets or Sets FullText
        /// </summary>
        [DataMember(Name = "fullText", EmitDefaultValue = false)]
        public string FullText { get; set; }

        /// <summary>
        /// Gets or Sets Segments
        /// </summary>
        [DataMember(Name = "segments", EmitDefaultValue = false)]
        public List<GetYouTubeTranscript200ResponseSegmentsInner> Segments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetYouTubeTranscript200Response {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  VideoId: ").Append(VideoId).Append("\n");
            sb.Append("  Language: ").Append(Language).Append("\n");
            sb.Append("  FullText: ").Append(FullText).Append("\n");
            sb.Append("  Segments: ").Append(Segments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
