/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// ImportWhatsAppContactsRequest
    /// </summary>
    [DataContract(Name = "importWhatsAppContacts_request")]
    public partial class ImportWhatsAppContactsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ImportWhatsAppContactsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ImportWhatsAppContactsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ImportWhatsAppContactsRequest" /> class.
        /// </summary>
        /// <param name="accountId">WhatsApp social account ID (required).</param>
        /// <param name="contacts">Contacts to import (max 1000) (required).</param>
        /// <param name="defaultTags">Tags applied to all imported contacts.</param>
        /// <param name="defaultGroups">Groups applied to all imported contacts.</param>
        /// <param name="skipDuplicates">Skip contacts with existing phone numbers (default to true).</param>
        public ImportWhatsAppContactsRequest(string accountId = default, List<ImportWhatsAppContactsRequestContactsInner> contacts = default, List<string> defaultTags = default, List<string> defaultGroups = default, bool skipDuplicates = true)
        {
            // to ensure "accountId" is required (not null)
            if (accountId == null)
            {
                throw new ArgumentNullException("accountId is a required property for ImportWhatsAppContactsRequest and cannot be null");
            }
            this.AccountId = accountId;
            // to ensure "contacts" is required (not null)
            if (contacts == null)
            {
                throw new ArgumentNullException("contacts is a required property for ImportWhatsAppContactsRequest and cannot be null");
            }
            this.Contacts = contacts;
            this.DefaultTags = defaultTags;
            this.DefaultGroups = defaultGroups;
            this.SkipDuplicates = skipDuplicates;
        }

        /// <summary>
        /// WhatsApp social account ID
        /// </summary>
        /// <value>WhatsApp social account ID</value>
        [DataMember(Name = "accountId", IsRequired = true, EmitDefaultValue = true)]
        public string AccountId { get; set; }

        /// <summary>
        /// Contacts to import (max 1000)
        /// </summary>
        /// <value>Contacts to import (max 1000)</value>
        [DataMember(Name = "contacts", IsRequired = true, EmitDefaultValue = true)]
        public List<ImportWhatsAppContactsRequestContactsInner> Contacts { get; set; }

        /// <summary>
        /// Tags applied to all imported contacts
        /// </summary>
        /// <value>Tags applied to all imported contacts</value>
        [DataMember(Name = "defaultTags", EmitDefaultValue = false)]
        public List<string> DefaultTags { get; set; }

        /// <summary>
        /// Groups applied to all imported contacts
        /// </summary>
        /// <value>Groups applied to all imported contacts</value>
        [DataMember(Name = "defaultGroups", EmitDefaultValue = false)]
        public List<string> DefaultGroups { get; set; }

        /// <summary>
        /// Skip contacts with existing phone numbers
        /// </summary>
        /// <value>Skip contacts with existing phone numbers</value>
        [DataMember(Name = "skipDuplicates", EmitDefaultValue = true)]
        public bool SkipDuplicates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ImportWhatsAppContactsRequest {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  Contacts: ").Append(Contacts).Append("\n");
            sb.Append("  DefaultTags: ").Append(DefaultTags).Append("\n");
            sb.Append("  DefaultGroups: ").Append(DefaultGroups).Append("\n");
            sb.Append("  SkipDuplicates: ").Append(SkipDuplicates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
