/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// RemoveWhatsAppBroadcastRecipients200Response
    /// </summary>
    [DataContract(Name = "removeWhatsAppBroadcastRecipients_200_response")]
    public partial class RemoveWhatsAppBroadcastRecipients200Response : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RemoveWhatsAppBroadcastRecipients200Response" /> class.
        /// </summary>
        /// <param name="success">success.</param>
        /// <param name="removed">Number of recipients removed.</param>
        /// <param name="totalRecipients">Remaining recipient count.</param>
        public RemoveWhatsAppBroadcastRecipients200Response(bool success = default, int removed = default, int totalRecipients = default)
        {
            this.Success = success;
            this.Removed = removed;
            this.TotalRecipients = totalRecipients;
        }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "success", EmitDefaultValue = true)]
        public bool Success { get; set; }

        /// <summary>
        /// Number of recipients removed
        /// </summary>
        /// <value>Number of recipients removed</value>
        [DataMember(Name = "removed", EmitDefaultValue = false)]
        public int Removed { get; set; }

        /// <summary>
        /// Remaining recipient count
        /// </summary>
        /// <value>Remaining recipient count</value>
        [DataMember(Name = "totalRecipients", EmitDefaultValue = false)]
        public int TotalRecipients { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RemoveWhatsAppBroadcastRecipients200Response {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  Removed: ").Append(Removed).Append("\n");
            sb.Append("  TotalRecipients: ").Append(TotalRecipients).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
