/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// ScheduleWhatsAppBroadcastRequest
    /// </summary>
    [DataContract(Name = "scheduleWhatsAppBroadcast_request")]
    public partial class ScheduleWhatsAppBroadcastRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduleWhatsAppBroadcastRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ScheduleWhatsAppBroadcastRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ScheduleWhatsAppBroadcastRequest" /> class.
        /// </summary>
        /// <param name="scheduledAt">ISO 8601 date-time for sending (must be in the future, max 30 days) (required).</param>
        public ScheduleWhatsAppBroadcastRequest(DateTime scheduledAt = default)
        {
            this.ScheduledAt = scheduledAt;
        }

        /// <summary>
        /// ISO 8601 date-time for sending (must be in the future, max 30 days)
        /// </summary>
        /// <value>ISO 8601 date-time for sending (must be in the future, max 30 days)</value>
        [DataMember(Name = "scheduledAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTime ScheduledAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ScheduleWhatsAppBroadcastRequest {\n");
            sb.Append("  ScheduledAt: ").Append(ScheduledAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
