/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// Requires a Public Profile. Media required for all content types (single item only, auto-encrypted). Content types: story (ephemeral 24h, no caption), saved_story (permanent, title max 45 chars), spotlight (video, description max 160 chars). Images max 20 MB (JPEG/PNG), videos max 500 MB (MP4, 5-60s, min 540x960px). 
    /// </summary>
    [DataContract(Name = "SnapchatPlatformData")]
    public partial class SnapchatPlatformData : IValidatableObject
    {
        /// <summary>
        /// Content type: story (ephemeral 24h, default), saved_story (permanent on Public Profile), spotlight (video feed)
        /// </summary>
        /// <value>Content type: story (ephemeral 24h, default), saved_story (permanent on Public Profile), spotlight (video feed)</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ContentTypeEnum
        {
            /// <summary>
            /// Enum Story for value: story
            /// </summary>
            [EnumMember(Value = "story")]
            Story = 1,

            /// <summary>
            /// Enum SavedStory for value: saved_story
            /// </summary>
            [EnumMember(Value = "saved_story")]
            SavedStory = 2,

            /// <summary>
            /// Enum Spotlight for value: spotlight
            /// </summary>
            [EnumMember(Value = "spotlight")]
            Spotlight = 3
        }


        /// <summary>
        /// Content type: story (ephemeral 24h, default), saved_story (permanent on Public Profile), spotlight (video feed)
        /// </summary>
        /// <value>Content type: story (ephemeral 24h, default), saved_story (permanent on Public Profile), spotlight (video feed)</value>
        [DataMember(Name = "contentType", EmitDefaultValue = false)]
        public ContentTypeEnum? ContentType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SnapchatPlatformData" /> class.
        /// </summary>
        /// <param name="contentType">Content type: story (ephemeral 24h, default), saved_story (permanent on Public Profile), spotlight (video feed) (default to ContentTypeEnum.Story).</param>
        public SnapchatPlatformData(ContentTypeEnum? contentType = ContentTypeEnum.Story)
        {
            this.ContentType = contentType;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SnapchatPlatformData {\n");
            sb.Append("  ContentType: ").Append(ContentType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
