/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// Carousels support up to 10 images (no videos). Single posts support one image or video. Videos must be H.264/AAC MP4, max 5 min. Images must be JPEG/PNG, max 8 MB. threadItems creates a reply chain.
    /// </summary>
    [DataContract(Name = "ThreadsPlatformData")]
    public partial class ThreadsPlatformData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ThreadsPlatformData" /> class.
        /// </summary>
        /// <param name="threadItems">Sequence of posts in a Threads thread (root then replies in order)..</param>
        public ThreadsPlatformData(List<TwitterPlatformDataThreadItemsInner> threadItems = default)
        {
            this.ThreadItems = threadItems;
        }

        /// <summary>
        /// Sequence of posts in a Threads thread (root then replies in order).
        /// </summary>
        /// <value>Sequence of posts in a Threads thread (root then replies in order).</value>
        [DataMember(Name = "threadItems", EmitDefaultValue = false)]
        public List<TwitterPlatformDataThreadItemsInner> ThreadItems { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ThreadsPlatformData {\n");
            sb.Append("  ThreadItems: ").Append(ThreadItems).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
