/*
 * Zernio API
 *
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// UpdateWhatsAppContactRequest
    /// </summary>
    [DataContract(Name = "updateWhatsAppContact_request")]
    public partial class UpdateWhatsAppContactRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateWhatsAppContactRequest" /> class.
        /// </summary>
        /// <param name="name">Contact name.</param>
        /// <param name="email">Contact email.</param>
        /// <param name="company">Company name.</param>
        /// <param name="tags">Tags (replaces existing).</param>
        /// <param name="groups">Groups (replaces existing).</param>
        /// <param name="isOptedIn">Opt-in status (changes are timestamped).</param>
        /// <param name="isBlocked">Block status.</param>
        /// <param name="customFields">Custom fields to merge (set value to null to remove a field).</param>
        /// <param name="notes">Notes about the contact.</param>
        public UpdateWhatsAppContactRequest(string name = default, string email = default, string company = default, List<string> tags = default, List<string> groups = default, bool isOptedIn = default, bool isBlocked = default, Dictionary<string, string> customFields = default, string notes = default)
        {
            this.Name = name;
            this.Email = email;
            this.Company = company;
            this.Tags = tags;
            this.Groups = groups;
            this.IsOptedIn = isOptedIn;
            this.IsBlocked = isBlocked;
            this.CustomFields = customFields;
            this.Notes = notes;
        }

        /// <summary>
        /// Contact name
        /// </summary>
        /// <value>Contact name</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Contact email
        /// </summary>
        /// <value>Contact email</value>
        [DataMember(Name = "email", EmitDefaultValue = false)]
        public string Email { get; set; }

        /// <summary>
        /// Company name
        /// </summary>
        /// <value>Company name</value>
        [DataMember(Name = "company", EmitDefaultValue = false)]
        public string Company { get; set; }

        /// <summary>
        /// Tags (replaces existing)
        /// </summary>
        /// <value>Tags (replaces existing)</value>
        [DataMember(Name = "tags", EmitDefaultValue = false)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Groups (replaces existing)
        /// </summary>
        /// <value>Groups (replaces existing)</value>
        [DataMember(Name = "groups", EmitDefaultValue = false)]
        public List<string> Groups { get; set; }

        /// <summary>
        /// Opt-in status (changes are timestamped)
        /// </summary>
        /// <value>Opt-in status (changes are timestamped)</value>
        [DataMember(Name = "isOptedIn", EmitDefaultValue = true)]
        public bool IsOptedIn { get; set; }

        /// <summary>
        /// Block status
        /// </summary>
        /// <value>Block status</value>
        [DataMember(Name = "isBlocked", EmitDefaultValue = true)]
        public bool IsBlocked { get; set; }

        /// <summary>
        /// Custom fields to merge (set value to null to remove a field)
        /// </summary>
        /// <value>Custom fields to merge (set value to null to remove a field)</value>
        [DataMember(Name = "customFields", EmitDefaultValue = false)]
        public Dictionary<string, string> CustomFields { get; set; }

        /// <summary>
        /// Notes about the contact
        /// </summary>
        /// <value>Notes about the contact</value>
        [DataMember(Name = "notes", EmitDefaultValue = false)]
        public string Notes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateWhatsAppContactRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Company: ").Append(Company).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  Groups: ").Append(Groups).Append("\n");
            sb.Append("  IsOptedIn: ").Append(IsOptedIn).Append("\n");
            sb.Append("  IsBlocked: ").Append(IsBlocked).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
