/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// Subreddit not found
    /// </summary>
    [DataContract(Name = "validateSubreddit_200_response_oneOf_1")]
    public partial class ValidateSubreddit200ResponseOneOf1 : IValidatableObject
    {
        /// <summary>
        /// Defines Exists
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ExistsEnum
        {
            /// <summary>
            /// Enum False for value: false
            /// </summary>
            False = false
        }


        /// <summary>
        /// Gets or Sets Exists
        /// </summary>
        [DataMember(Name = "exists", EmitDefaultValue = true)]
        public ExistsEnum? Exists { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ValidateSubreddit200ResponseOneOf1" /> class.
        /// </summary>
        /// <param name="exists">exists.</param>
        /// <param name="error">error.</param>
        public ValidateSubreddit200ResponseOneOf1(ExistsEnum? exists = default, string error = default)
        {
            this.Exists = exists;
            this.Error = error;
        }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", EmitDefaultValue = false)]
        public string Error { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ValidateSubreddit200ResponseOneOf1 {\n");
            sb.Append("  Exists: ").Append(Exists).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
