/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// WebhookPayloadAccountConnectedAccount
    /// </summary>
    [DataContract(Name = "WebhookPayloadAccountConnected_account")]
    public partial class WebhookPayloadAccountConnectedAccount : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookPayloadAccountConnectedAccount" /> class.
        /// </summary>
        /// <param name="accountId">The account&#39;s unique identifier (same as used in /v1/accounts/{accountId}).</param>
        /// <param name="profileId">The profile&#39;s unique identifier this account belongs to.</param>
        /// <param name="platform">platform.</param>
        /// <param name="username">username.</param>
        /// <param name="displayName">displayName.</param>
        public WebhookPayloadAccountConnectedAccount(string accountId = default, string profileId = default, string platform = default, string username = default, string displayName = default)
        {
            this.AccountId = accountId;
            this.ProfileId = profileId;
            this.Platform = platform;
            this.Username = username;
            this.DisplayName = displayName;
        }

        /// <summary>
        /// The account&#39;s unique identifier (same as used in /v1/accounts/{accountId})
        /// </summary>
        /// <value>The account&#39;s unique identifier (same as used in /v1/accounts/{accountId})</value>
        [DataMember(Name = "accountId", EmitDefaultValue = false)]
        public string AccountId { get; set; }

        /// <summary>
        /// The profile&#39;s unique identifier this account belongs to
        /// </summary>
        /// <value>The profile&#39;s unique identifier this account belongs to</value>
        [DataMember(Name = "profileId", EmitDefaultValue = false)]
        public string ProfileId { get; set; }

        /// <summary>
        /// Gets or Sets Platform
        /// </summary>
        [DataMember(Name = "platform", EmitDefaultValue = false)]
        public string Platform { get; set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [DataMember(Name = "username", EmitDefaultValue = false)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [DataMember(Name = "displayName", EmitDefaultValue = false)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebhookPayloadAccountConnectedAccount {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  ProfileId: ").Append(ProfileId).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
