/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// Interactive message metadata (present when message is a quick reply tap, postback button tap, or inline keyboard callback)
    /// </summary>
    [DataContract(Name = "WebhookPayloadMessage_metadata")]
    public partial class WebhookPayloadMessageMetadata : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookPayloadMessageMetadata" /> class.
        /// </summary>
        /// <param name="quickReplyPayload">Payload from a quick reply tap (Meta platforms).</param>
        /// <param name="postbackPayload">Payload from a postback button tap (Meta platforms).</param>
        /// <param name="postbackTitle">Title of the tapped postback button (Meta platforms).</param>
        /// <param name="callbackData">Callback data from an inline keyboard button tap (Telegram).</param>
        public WebhookPayloadMessageMetadata(string quickReplyPayload = default, string postbackPayload = default, string postbackTitle = default, string callbackData = default)
        {
            this.QuickReplyPayload = quickReplyPayload;
            this.PostbackPayload = postbackPayload;
            this.PostbackTitle = postbackTitle;
            this.CallbackData = callbackData;
        }

        /// <summary>
        /// Payload from a quick reply tap (Meta platforms)
        /// </summary>
        /// <value>Payload from a quick reply tap (Meta platforms)</value>
        [DataMember(Name = "quickReplyPayload", EmitDefaultValue = false)]
        public string QuickReplyPayload { get; set; }

        /// <summary>
        /// Payload from a postback button tap (Meta platforms)
        /// </summary>
        /// <value>Payload from a postback button tap (Meta platforms)</value>
        [DataMember(Name = "postbackPayload", EmitDefaultValue = false)]
        public string PostbackPayload { get; set; }

        /// <summary>
        /// Title of the tapped postback button (Meta platforms)
        /// </summary>
        /// <value>Title of the tapped postback button (Meta platforms)</value>
        [DataMember(Name = "postbackTitle", EmitDefaultValue = false)]
        public string PostbackTitle { get; set; }

        /// <summary>
        /// Callback data from an inline keyboard button tap (Telegram)
        /// </summary>
        /// <value>Callback data from an inline keyboard button tap (Telegram)</value>
        [DataMember(Name = "callbackData", EmitDefaultValue = false)]
        public string CallbackData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebhookPayloadMessageMetadata {\n");
            sb.Append("  QuickReplyPayload: ").Append(QuickReplyPayload).Append("\n");
            sb.Append("  PostbackPayload: ").Append(PostbackPayload).Append("\n");
            sb.Append("  PostbackTitle: ").Append(PostbackTitle).Append("\n");
            sb.Append("  CallbackData: ").Append(CallbackData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
