/*
 * Late API
 *
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Late.Client.FileParameter;
using OpenAPIDateConverter = Late.Client.OpenAPIDateConverter;

namespace Late.Model
{
    /// <summary>
    /// YouTube video upload settings: - Videos ≤ 3 minutes are automatically detected as YouTube Shorts - Videos &gt; 3 minutes become regular YouTube videos - Custom thumbnails supported for regular videos (via mediaItem.thumbnail) - Custom thumbnails NOT supported for Shorts via API - Scheduled videos are uploaded immediately as the specified visibility and published at scheduled time - Visibility defaults to \&quot;public\&quot; if not specified - madeForKids defaults to false (not child-directed) - Set containsSyntheticMedia: true if your video contains AI-generated content 
    /// </summary>
    [DataContract(Name = "YouTubePlatformData")]
    public partial class YouTubePlatformData : IValidatableObject
    {
        /// <summary>
        /// Video visibility setting: - public: Anyone can search for and watch (default) - unlisted: Only people with the link can watch - private: Only you and people you specifically share with can watch 
        /// </summary>
        /// <value>Video visibility setting: - public: Anyone can search for and watch (default) - unlisted: Only people with the link can watch - private: Only you and people you specifically share with can watch </value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum VisibilityEnum
        {
            /// <summary>
            /// Enum Public for value: public
            /// </summary>
            [EnumMember(Value = "public")]
            Public = 1,

            /// <summary>
            /// Enum Private for value: private
            /// </summary>
            [EnumMember(Value = "private")]
            Private = 2,

            /// <summary>
            /// Enum Unlisted for value: unlisted
            /// </summary>
            [EnumMember(Value = "unlisted")]
            Unlisted = 3
        }


        /// <summary>
        /// Video visibility setting: - public: Anyone can search for and watch (default) - unlisted: Only people with the link can watch - private: Only you and people you specifically share with can watch 
        /// </summary>
        /// <value>Video visibility setting: - public: Anyone can search for and watch (default) - unlisted: Only people with the link can watch - private: Only you and people you specifically share with can watch </value>
        [DataMember(Name = "visibility", EmitDefaultValue = false)]
        public VisibilityEnum? Visibility { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="YouTubePlatformData" /> class.
        /// </summary>
        /// <param name="title">Video title. Defaults to first line of content or \&quot;Untitled Video\&quot;. Must be ≤ 100 characters..</param>
        /// <param name="visibility">Video visibility setting: - public: Anyone can search for and watch (default) - unlisted: Only people with the link can watch - private: Only you and people you specifically share with can watch  (default to VisibilityEnum.Public).</param>
        /// <param name="madeForKids">COPPA compliance: Audience designation for the video. - true: Video is made for kids (child-directed content) - false: Video is NOT made for kids (default)  This field maps to YouTube&#39;s &#x60;selfDeclaredMadeForKids&#x60; setting. Videos marked as made for kids have restricted features (no comments, no notifications, limited ad targeting).  IMPORTANT: If not specified, defaults to false. YouTube requires this to be explicitly set, otherwise the video may be blocked from views until configured in YouTube Studio.  (default to false).</param>
        /// <param name="firstComment">Optional first comment to post immediately after video upload. Up to 10,000 characters (YouTube&#39;s comment limit)..</param>
        /// <param name="containsSyntheticMedia">AI-generated content disclosure flag. Set to true if your video contains AI-generated or synthetic content that could be mistaken for real people, places, or events. This helps viewers understand when realistic content has been created or altered using AI. YouTube may add a label to videos when this is set. Added to YouTube Data API in October 2024.  (default to false).</param>
        /// <param name="categoryId">YouTube video category ID. Defaults to &#39;22&#39; (People &amp; Blogs). Common categories: 1 (Film &amp; Animation), 2 (Autos &amp; Vehicles), 10 (Music), 15 (Pets &amp; Animals), 17 (Sports), 20 (Gaming), 22 (People &amp; Blogs), 23 (Comedy), 24 (Entertainment), 25 (News &amp; Politics), 26 (Howto &amp; Style), 27 (Education), 28 (Science &amp; Technology).  (default to &quot;22&quot;).</param>
        public YouTubePlatformData(string title = default, VisibilityEnum? visibility = VisibilityEnum.Public, bool madeForKids = false, string firstComment = default, bool containsSyntheticMedia = false, string categoryId = @"22")
        {
            this.Title = title;
            this.Visibility = visibility;
            this.MadeForKids = madeForKids;
            this.FirstComment = firstComment;
            this.ContainsSyntheticMedia = containsSyntheticMedia;
            // use default value if no "categoryId" provided
            this.CategoryId = categoryId ?? @"22";
        }

        /// <summary>
        /// Video title. Defaults to first line of content or \&quot;Untitled Video\&quot;. Must be ≤ 100 characters.
        /// </summary>
        /// <value>Video title. Defaults to first line of content or \&quot;Untitled Video\&quot;. Must be ≤ 100 characters.</value>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// COPPA compliance: Audience designation for the video. - true: Video is made for kids (child-directed content) - false: Video is NOT made for kids (default)  This field maps to YouTube&#39;s &#x60;selfDeclaredMadeForKids&#x60; setting. Videos marked as made for kids have restricted features (no comments, no notifications, limited ad targeting).  IMPORTANT: If not specified, defaults to false. YouTube requires this to be explicitly set, otherwise the video may be blocked from views until configured in YouTube Studio. 
        /// </summary>
        /// <value>COPPA compliance: Audience designation for the video. - true: Video is made for kids (child-directed content) - false: Video is NOT made for kids (default)  This field maps to YouTube&#39;s &#x60;selfDeclaredMadeForKids&#x60; setting. Videos marked as made for kids have restricted features (no comments, no notifications, limited ad targeting).  IMPORTANT: If not specified, defaults to false. YouTube requires this to be explicitly set, otherwise the video may be blocked from views until configured in YouTube Studio. </value>
        [DataMember(Name = "madeForKids", EmitDefaultValue = true)]
        public bool MadeForKids { get; set; }

        /// <summary>
        /// Optional first comment to post immediately after video upload. Up to 10,000 characters (YouTube&#39;s comment limit).
        /// </summary>
        /// <value>Optional first comment to post immediately after video upload. Up to 10,000 characters (YouTube&#39;s comment limit).</value>
        [DataMember(Name = "firstComment", EmitDefaultValue = false)]
        public string FirstComment { get; set; }

        /// <summary>
        /// AI-generated content disclosure flag. Set to true if your video contains AI-generated or synthetic content that could be mistaken for real people, places, or events. This helps viewers understand when realistic content has been created or altered using AI. YouTube may add a label to videos when this is set. Added to YouTube Data API in October 2024. 
        /// </summary>
        /// <value>AI-generated content disclosure flag. Set to true if your video contains AI-generated or synthetic content that could be mistaken for real people, places, or events. This helps viewers understand when realistic content has been created or altered using AI. YouTube may add a label to videos when this is set. Added to YouTube Data API in October 2024. </value>
        [DataMember(Name = "containsSyntheticMedia", EmitDefaultValue = true)]
        public bool ContainsSyntheticMedia { get; set; }

        /// <summary>
        /// YouTube video category ID. Defaults to &#39;22&#39; (People &amp; Blogs). Common categories: 1 (Film &amp; Animation), 2 (Autos &amp; Vehicles), 10 (Music), 15 (Pets &amp; Animals), 17 (Sports), 20 (Gaming), 22 (People &amp; Blogs), 23 (Comedy), 24 (Entertainment), 25 (News &amp; Politics), 26 (Howto &amp; Style), 27 (Education), 28 (Science &amp; Technology). 
        /// </summary>
        /// <value>YouTube video category ID. Defaults to &#39;22&#39; (People &amp; Blogs). Common categories: 1 (Film &amp; Animation), 2 (Autos &amp; Vehicles), 10 (Music), 15 (Pets &amp; Animals), 17 (Sports), 20 (Gaming), 22 (People &amp; Blogs), 23 (Comedy), 24 (Entertainment), 25 (News &amp; Politics), 26 (Howto &amp; Style), 27 (Education), 28 (Science &amp; Technology). </value>
        [DataMember(Name = "categoryId", EmitDefaultValue = false)]
        public string CategoryId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class YouTubePlatformData {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Visibility: ").Append(Visibility).Append("\n");
            sb.Append("  MadeForKids: ").Append(MadeForKids).Append("\n");
            sb.Append("  FirstComment: ").Append(FirstComment).Append("\n");
            sb.Append("  ContainsSyntheticMedia: ").Append(ContainsSyntheticMedia).Append("\n");
            sb.Append("  CategoryId: ").Append(CategoryId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Title (string) maxLength
            if (this.Title != null && this.Title.Length > 100)
            {
                yield return new ValidationResult("Invalid value for Title, length must be less than 100.", new [] { "Title" });
            }

            // FirstComment (string) maxLength
            if (this.FirstComment != null && this.FirstComment.Length > 10000)
            {
                yield return new ValidationResult("Invalid value for FirstComment, length must be less than 10000.", new [] { "FirstComment" });
            }

            yield break;
        }
    }

}
